### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by quentfr21** [SteveKunG/MorePlanets#1]
hello

More-Planets-1.7.10-1.3.2

missing texture on multiple planet

fixed by take old texture from old release
just let you know

thanks

**Comment by MJRLegends** [comment]
@quentfr21 they were removed for a reason, so adding them back in is not really a good idea and kinda edits @SteveKunG mod which your not allowed to do

**Comment by quentfr21** [comment]
@MJRLegends 

thanks for the info, i only added it for me , i will try and if i got an issue related to it i will return to not modified release version but i just add some assets back i think this will not cause an issue but maybe :)

thanks

**Comment by SteveKunG** [comment]
Thanks for your help @MJRLegends
