### ISSUE TITLE
The server crashed. Crashlog points to MorePlanet Packages

### ISSUE THREAD

**Issue by DeltaVetal26** [SteveKunG/MorePlanets#1]
Good day! I installed MorePlanets on my server, started it, everything seemed fine, I flew a bit around the usual world and the server suddenly fell. In the cachet it indicates: java.lang.NoClassDefFoundError: net / minecraft / client / entity / EntityPlayerSP
At stevekung.mods.moreplanets.network.PacketSimpleMP.handleServerSide (PacketSimpleMP.java:165)
The full krashlog attached at the bottom.
Server version: 1.10.2
Kernel version: spongeforge-1.10.2-2281-5.2.0-BETA-2401
MorePlanets related modes:
- GalacticraftCore-1.10.2-4.0.0.110
- Galacticraft-Planets-1.10.2-4.0.0.110
- MicdoodleCore-1.10.2-4.0.0.110
- More-Planets-1.10.2-2.0.5-GC110
I will be very grateful to you for your help!
[crash-2017-07-03_13.47.33-server.txt](https://github.com/SteveKunG/MorePlanets/files/1118675/crash-2017-07-03_13.47.33-server.txt)

**Comment by SteveKunG** [comment]
OK, Then please try this version.
https://minecraft.curseforge.com/projects/galacticraft-add-on-more-planets/files/2445328

I will reopen if this still an issue. Thank you!
