### ISSUE TITLE
Gravity Boots crashes game, when in inventory

### ISSUE THREAD

**Issue by nidico100** [SteveKunG/MorePlanets#10]
newest galacticraft version is installed

http://pastebin.com/wsUZT875

**Comment by SteveKunG** [comment]
Still can't reproduce in my development with latest Galacticraft source code. :(

**Comment by nidico100** [comment]
ftb thirdparty modpack
code: thenewworld
there the problem exists

**Comment by SteveKunG** [comment]
OK. Please test if you still getting a problem.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2358057-more-planets-mod-v-1-3-1-galacticraft-add-on?page=50#c1015
