### ISSUE TITLE
rocket tiers

### ISSUE THREAD

**Issue by SpongebobFan123** [SteveKunG/MorePlanets#10]
This mod is fantastic with the Sirius solar system, but whenever I use this with Extra Planets, the rockets get SUPER OP.  For example, the tier 4 rocket, which is only supposed to go only up to Jupiter, now goes all the way to DIONA. So do u think u can add a config option that lets us set the planet/rocket/schematic tiers so that we could make Diona a tier 10 planet and have it's dungeon have a tier 11 schematic and so on? It would be really awesome if u added this. 

From, one of your biggest fans. @SteveKunG

**Comment by SteveKunG** [comment]
Maybe I should implement this in 1.10+. I want to rewrite all the things in my mod :)

**Comment by SpongebobFan123** [comment]
It would be great to see that! But.. I'm playing this in 1.7.10 so could you put it in that version too?

**Comment by SpongebobFan123** [comment]
Oh yeah, and why don't we make a separate launch pad for the mo planets rockets (plasma rockets, as how I like to call them) so that we could make them look more harder(or easier) and make them more awesomer?

**Comment by SpongebobFan123** [comment]
oh yeah by the way turns out that if you defeat the boss in the moon, it can give u any random schematic, like a tier 4 one. that means that you wont have to defeat the tier 4 boss. from the way I see it, that's BROKEN. so could you put a config option so that all bosses will only have the schematics of the next tier?

**Comment by SteveKunG** [comment]
So I've implemented this in here https://github.com/SteveKunG/MorePlanets/commit/344cc5837908165f5bd4c1724f16b6b3de03c7f3.
