### ISSUE TITLE
Fronos is missing 

### ISSUE THREAD

**Issue by theradpickle** [SteveKunG/MorePlanets#100]
the blocks are there but not the actual planet

**Comment by theradpickle** [comment]
Mod Versions:
Steve Version: SteveKunG's-Lib-1.12.2-1.1.9
More Planets Version: More-Planets-1.12.2-2.1.14-GC261

**Comment by theradpickle** [comment]
not sure if it hasn't been implemented yet but i just wanted to make sure

**Comment by SteveKunG** [comment]
Added in 2.2.0 :)
