### ISSUE TITLE
Black hole storage dupe

### ISSUE THREAD

**Issue by bigenergy** [SteveKunG/MorePlanets#101]
https://www.youtube.com/watch?v=VXvJhFWtTG0&feature=youtu.be

**Comment by SteveKunG** [comment]
Tested with Advanced Solar Panels and IC2 mod is fine, Are you really sure that is happened only my mod?
Because Black Hole Storage use the same code from Hopper.

**Comment by bigenergy** [comment]
> Tested with Advanced Solar Panels and IC2 mod is fine, Are you really sure that is happened only my mod?
> Because Black Hole Storage use the same code from Hopper.

this works with any item in the game

**Comment by TheComputerizer** [comment]
I have come across this exact same issue in [my pack](https://www.curseforge.com/minecraft/modpacks/dimensionhopper). Items that are pulled into storage get multiplied by 10
