### ISSUE TITLE
Mixin crash

### ISSUE THREAD

**Issue by bigenergy** [SteveKunG/MorePlanets#102]
More-Planets-1.12.2-2.2.0-GC281
https://pastebin.com/RReL6y5i

More-Planets-1.12.2-2.0.24-GC251 working excellent

**Comment by bigenergy** [comment]
you should update mixin to 0.8

**Comment by SteveKunG** [comment]
Try this
https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

**Comment by bigenergy** [comment]
> Try this
> https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

I certainly know about this, but you still better update the mixin, since using a different mod looks like a crutch

**Comment by SteveKunG** [comment]
Is there any good reason why I should update mixin to 0.8? I don’t see problems with it.

**Comment by bigenergy** [comment]
> Is there any good reason why I should update mixin to 0.8? I don’t see problems with it.

Almost all mods that used mixin have been updated to 0.8

**Comment by SteveKunG** [comment]
No, that's not a good reason to update mixin to 0.8 because of "all mods that used mixin 0.8"
