### ISSUE TITLE
Performance problem

### ISSUE THREAD

**Issue by bigenergy** [SteveKunG/MorePlanets#104]
![image](https://user-images.githubusercontent.com/17977139/102478281-79dc6800-406e-11eb-9b7f-283b6e32cd61.png)

https://spark.lucko.me/#8pdvkGLbQA

**Comment by SteveKunG** [comment]
Please test with experimental build in my discord, go to #more-planets channel.

**Comment by bigenergy** [comment]
> Please test with experimental build in my discord, go to #more-planets channel.

It seems to have gotten much better.

**Comment by bigenergy** [comment]
https://spark.lucko.me/#yIpu63cPir
I was wrong, there are still server drawdowns up to 12 tps

**Comment by bigenergy** [comment]
![image](https://user-images.githubusercontent.com/17977139/102718531-abb52f00-42f9-11eb-9417-1410d60baf96.png)

**Comment by SteveKunG** [comment]
Ok, I get rid out of java .stream(). So please try with latest performance fix in my discord.

**Comment by bigenergy** [comment]
> Ok, I get rid out of java .stream(). So please try with latest performance fix in my discord.

I tested everything seems to be fine now

**Comment by SteveKunG** [comment]
Ok, keep reporting the result then. Just wanted to confirm if there is no side effect on your server.

**Comment by bigenergy** [comment]
> Ok, keep reporting the result then. Just wanted to confirm if there is no side effect on your server.

I haven't found any errors yet, everything seems to work stably

**Comment by SteveKunG** [comment]
Please update to 2.2.1.
https://www.curseforge.com/minecraft/mc-mods/more-planets-gc-addon/files/3165054
