### ISSUE TITLE
Will not launch, exit code: 0

### ISSUE THREAD

**Issue by andrewduong2001** [SteveKunG/MorePlanets#105]
This is all I get from the log, there is no crash report generated. I am on build 281 of Galacticraft and More Planets.

[latest.log](https://github.com/SteveKunG/MorePlanets/files/5745361/latest.log)

**Comment by SteveKunG** [comment]
Try this mod
https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility
