### ISSUE TITLE
Galacticraft version 281 is broken, is it possible to backport to 280?

### ISSUE THREAD

**Issue by AxolotlAccount** [SteveKunG/MorePlanets#108]
In Galacticraft version 281, moon boss doesn't spawn and dungeons are broken. And the latest version of MorePlanets needs version 281. 

Backporting latest version to Galacticraft 280 would fix this issue.

**Comment by SteveKunG** [comment]
Please update to 2.2.1.
https://www.curseforge.com/minecraft/mc-mods/more-planets-gc-addon/files/3165054
