### ISSUE TITLE
SSP can only be joined one time after game start 

### ISSUE THREAD

**Issue by nidico100** [SteveKunG/MorePlanets#11]
after starting game you can only join ssp one time and then have to restart to join ssp again, else it would just open the main menu instead of the world

i removed any other mod to look which mod this is causing and when i removed moreplanets only, everything worked

**Comment by SteveKunG** [comment]
Did you have game log? It would be help to find bugs.

**Comment by nidico100** [comment]
i will send it later, when i'm at home

**Comment by nidico100** [comment]
I deleted all old logs and started game, then SSP then quit SSP again and tried to join SSP again and here are all logs, that where created during this time:

[logs.zip](https://github.com/SteveKunG/MorePlanets/files/578809/logs.zip)

**Comment by SteveKunG** [comment]
[17:52:23] [Server thread/ERROR] [FML/]: Caught exception from MineTweaker3

`java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =class java.util.Arrays$ArrayList id= 495988854 hashCode= 273024205 toString= [cofh.thermalexpansion.util.crafting.SmelterManager$ComparableItemStackSmelter@1360696412{m:0, i:net.minecraft.item.ItemBlock@1428223605, v:15}, cofh.thermalexpansion.util.crafting.SmelterManager$ComparableItemStackSmelter@1708149206{m:20, i:cofh.core.item.ItemBase@918994487, v:4166}]; object #2 =class java.util.Arrays$ArrayList id= 10439709 hashCode= 273024205 toString= [cofh.thermalexpansion.util.crafting.SmelterManager$ComparableItemStackSmelter@479256568{m:0, i:net.minecraft.item.ItemBlock@1428223605, v:15}, cofh.thermalexpansion.util.crafting.SmelterManager$ComparableItemStackSmelter@430772290{m:20, i:cofh.core.item.ItemBase@918994487, v:4166}]`

Not More Planets issue.
