### ISSUE TITLE
Minecraft failed to start!  More-Planets-1.12.2-2.2.1-GC280 (1.12.2)

### ISSUE THREAD

**Issue by romashulman** [SteveKunG/MorePlanets#110]
Guys
can you help with this issue 
Please

![printscr](https://user-images.githubusercontent.com/77308429/104325822-e300a100-549d-11eb-82c0-7941a73055be.png)

[crash-2021-01-12_06.09.42-client.txt](https://github.com/SteveKunG/MorePlanets/files/5802604/crash-2021-01-12_06.09.42-client.txt)

[latest.log](https://github.com/SteveKunG/MorePlanets/files/5802593/latest.log)

**Comment by SteveKunG** [comment]
I already told you to install JustEnoughIDs or NotEnoughIDs. -.-

**Comment by romashulman** [comment]
sorry i didn't see your previous comment

**Comment by romashulman** [comment]
![printscr](https://user-images.githubusercontent.com/77308429/104358099-da6e9180-54c2-11eb-8ec2-c26e71a9c4c7.png)


[crash-2021-01-12_10.39.06-client.txt](https://github.com/SteveKunG/MorePlanets/files/5804103/crash-2021-01-12_10.39.06-client.txt)
[debug.log](https://github.com/SteveKunG/MorePlanets/files/5804105/debug.log)
[latest.log](https://github.com/SteveKunG/MorePlanets/files/5804106/latest.log)

**Comment by SteveKunG** [comment]
Try to install this.

https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

**Comment by romashulman** [comment]
it did run with NotEnoughIDs-1.5.4.4
Thank You
but with [___MixinCompat-0.8___].jar still has crash
[crash-2021-01-12_11.29.13-client.txt](https://github.com/SteveKunG/MorePlanets/files/5804372/crash-2021-01-12_11.29.13-client.txt)
