### ISSUE TITLE
Minecraft not launching with skyblockcatia and patcher 1.5.1

### ISSUE THREAD

**Issue by L3gendsScorpio** [SteveKunG/MorePlanets#111]
Title. When will the problem be fixed.

**Comment by SteveKunG** [comment]
Instead of provide useless information, just PROVIDE your mod list or crash logs -.-

I use patcher 1.5.1 and doesn't crash any crash
![image](https://user-images.githubusercontent.com/6128413/104358938-abe3cb80-5541-11eb-9184-2a9d35e7ea99.png)
