### ISSUE TITLE
Can't access planets

### ISSUE THREAD

**Issue by Cosmology2727** [SteveKunG/MorePlanets#113]
When going to the solar system screen, I can't choose any of the new planets. The mod is definitely installed (it even gives the popup for updating it with that new update that just came out). Is there a trick to accessing them or something? I don't see anything on the page here,

**Comment by SteveKunG** [comment]
Did you install any others addon? Some are changing celestial selection screen.

**Comment by beetweenlands** [comment]
same

**Comment by beetweenlands** [comment]
except i don't have any other addons
