### ISSUE TITLE
No Tier 4+ items available

### ISSUE THREAD

**Issue by airandfingers** [SteveKunG/MorePlanets#116]
Hi, I've got a fresh 1.12.2 server with only Galacticraft and your mods installed:

* GalacticraftCore-1.12.2-4.0.2.280.jar
* Galacticraft-Planets-1.12.2-4.0.2.280.jar
* MicdoodleCore-1.12.2-4.0.2.280.jar
* More-Planets-1.12.2-2.2.1-GC280.jar
* SteveKunG's-Lib-1.12.2-1.1.9.jar

However, when I join the server with a client using Forge 1.12.2 14.23.5.2854 and the same mods, I don't see any tier 4-8 items, via looking them up in Creative Mode or any other method.

It looks like I should be able to just get a [Tier 4 Rocket](https://wiki.micdoodle8.com/wiki/Tier_4_Rocket) and the parts to create it, so this is a bug, right?

**Comment by airandfingers** [comment]
Follow-up question: Is there some way to get to other planets like Jupiter without using a Tier 4 rocket, e.g. using commands or some other item?

**Comment by airandfingers** [comment]
As evidence that the mod is actually loaded, it shows up in the list of mods on the client, I can get most items via the "More Planets Items" and "More Planets Blocks" pages from Creative mode, and I can use `/summon` to summon any of the mobs. 

The Planet Selection Screen shows the same planets as Galacticraft without More Planets, with no other solar systems.

I did find a workaround though, thanks to Journeymap! I create a bookmark (B), but change the dimension to another one in the "Dimensions" list, e.g. planet.chalos. Then, I open the bookmark manager (Ctrl+B/Cmd+b), switch the view to "Dimensions: All", and I can teleport to my bookmark on Chalos!

**Comment by beetweenlands** [comment]
same

**Comment by ROMVoid95** [comment]
Can you show a screenshot of the celestial map zoomed all the way out?

for the tier stuff, rockets were removed from the mod.

**Comment by SteveKunG** [comment]
Thanks @ROMVoid95 again, All Tiered Rockets has been removed entirely from the mod.
Did you install any others addon? I don't know what's going on.
