### ISSUE TITLE
Just some simple why questions

### ISSUE THREAD

**Issue by LinuxSquare** [SteveKunG/MorePlanets#117]
Hey there @SteveKunG 

First of all, a fantastic mod you've created. But I've got a few questions about the updates that you've made in the past.
I'm currently playing a modpack with the 1.7.10 version of this mod and next to it I'm creating a modpack with the 1.12.2 version with this mod. (Apocalypse-like modpacks, barren wasteland earth and trying to escape to space)

You might think now, "Oh no, did you ever read the Changelogs?" ~ No I didn't 😄 
But nevertheless here are my questions:

1.) In the 1.7.10 Version of More Planets, Fronos is a very colourful planet with candy-biomes, villages and villagers and ofc. boss-dungeons.
![image](https://user-images.githubusercontent.com/39629672/112124142-50c5f900-8bc2-11eb-9458-3a6d00da7c3a.png)

Now, in the 1.12.2 version, there are some things missing. For example the candy-biome, the villages with it's villagers. I couldn't find them neither in the creative tab nor in JEI.
![image](https://user-images.githubusercontent.com/39629672/112124393-94206780-8bc2-11eb-804c-7ccf2c541880.png)

It's not, that I don't like all of the changes, (maybe you got more important stuff to do), but I wish Fronos was like the Fronos of 1.7.10.

2.) There seems to be already an issue with this (#116 ) but, the mod seems to be working so far for me, otherwise I couldn't travel to Fronos and beyond. My concern relates to the Tier 4+ Rockets. In the 1.7.10 Version of More Planets there were rockets up to tier 8. And Fronos was tier 7 (as you might know). 
Now with the 1.12.2 Version, every planet is with the standard tier 3 rocket reachable.

The reason why I'm telling you this is, that I'm planing to make my modpack as hard as possible. For example using [Planet Progression from MJRLegends](https://www.curseforge.com/minecraft/mc-mods/planet-progression) and ofc Lost Cities in the Wasteland mode. My plan is, to make earth as hostile as possible so that there is no reason to stay on it. By having only 3 tiers of rockets, it's easy to get to an earth-like planet like Fronos or to any other.

I don't know if there are any plans "to bring them back" or to make it a little harder to reach more planets. (Or if it's configurable).
But I would be happy for any answer you can tell.

I thank you in advance for taking time for me.

Greetings from Switzerland
LinuxSquare

**Comment by ROMVoid95** [comment]
rockets were removed from the mod, so the tier is 3 to allow players who don't have other addons installed that add tier 4+ rockets to travel to the planets.

**Comment by SteveKunG** [comment]
Thanks to @ROMVoid95 again!

1. The reason I don't add candy biomes in 1.12.2 because it doesn't fit with Galacticraft style. Its too much fantasy + doesn't make any sense. I'm gonna make a Google Form later to hear players feedback.

For now, Fronos is much better in my opinion. I want to make it Earth-like planet with new creatures and more stuff. But still lack of features.

2. You can set planet tier to whatever you want in the config, If you played with other addons.

I'm thinking new stuff in 1.16, if you want to suggest anything to make my mod better please consider join my discord. Thank you!
https://discord.gg/6JhEjeY

**Comment by LinuxSquare** [comment]
Hi @SteveKunG and @ROMVoid95 

Thank you for your detailed answer.
I can clearly understand your decision to make Fronos an Earth-Like Planet and not a colourful one.
I'm exited for the new content you'll add to MorePlanets.

Thank you for your time writing this awesome mod and publishing it for free.

Kind regards from Switzerland
LinuxSquare
