### ISSUE TITLE
1.7.10 Crashes with Exitcode 0 

### ISSUE THREAD

**Issue by Dragongameryeet** [SteveKunG/MorePlanets#118]
I tried to install MixinCompat but that doesn't worked either.

**Comment by LinuxSquare** [comment]
Howdy @Dragongameryeet 

It's a pity that it doesn't work.

But it would be useful, if you could post some more information such as:
* The active mods you've installed alongside MorePlanets, Galacticraft & MixinCompat (including the release-tag of each mod)
  * e.g.
  * GalacticraftCore-1.7-3.0.12.504
  * Galacticraft-Planets-1.7-3.0.12.504
  * MicdoodleCore-1.7-3.0.12.504
  * More-Planets-1.7.10-1.4.4-GC502
  * etc.
* The Crash log as a [paste.ubuntu.com](https://paste.ubuntu.com/) / [paste.gg](https://paste.gg/) link or as a code-tag inside here.
  * Windows:
    * If it's technic: `%appdata%\.technic\modpacks\<name-of-modpack>\logs\latest.log`
    * If it's Minecraft: `%appdata%\.minecraft\logs\latest.log`
  * Linux:
    * If it's technic: `~/.technic/modpacks/<name-of-modpack>/logs/latest.log`
    * If it's Minecraft: `~/.minecraft/logs/latest.log`

So he can best evaluate if it's MorePlanets or another mod causing your issue.

**Comment by SteveKunG** [comment]
1.7.10 doesn't have mixin module. So as @LinuxSquare suggests, I need more info to reproduce the issue.
Since my last test 1.7.10 doesn't seems to crash.
![image](https://user-images.githubusercontent.com/6128413/124096816-23bc9880-da85-11eb-9832-64279eb1c6f3.png)
