### ISSUE TITLE
1.12.2 Crashes after updating to new version

### ISSUE THREAD

**Issue by HenrikoMagnifico** [SteveKunG/MorePlanets#119]
The game crashes when loading an older world made with a previous version of More Planets. Happens both on Single Player and Multiplayer.

Previous version: More-Planets-1.12.2-2.0.21-GC224.jar
Current version: More-Planets-1.12.2-2.2.1-GC280.jar

Crash log:
[crash-2021-04-10_15.43.35-server.txt](https://github.com/SteveKunG/MorePlanets/files/6289969/crash-2021-04-10_15.43.35-server.txt)

**Comment by HenrikoMagnifico** [comment]
> Personal note; I just want to salvage this world and make it playable with newer versions of More Planets. I do not mind deleting the blocks responsible for the crash, but I do not know what blocks they are.

**Comment by SteveKunG** [comment]
Did you have a full log? I don't think its from More Planets.

**Comment by SteveKunG** [comment]
Please reopen if you still has a problem.
