### ISSUE TITLE
Most content missing

### ISSUE THREAD

**Issue by Hamsterpouch** [SteveKunG/MorePlanets#122]
Hello. I have downloaded more planets addon. However, only a few things work. All 4-8 tier rocket and rocket parts don't appear. The Ion Cannon schematic doesn't work (can't add to NASA workbench). Also, only a few planets show up. (Nibiru, Fronos, Koentus, and Diona.) Many armor/tool sets are missing as well. Many other things are missing as well (ingots, plates, ores)
![Screenshot (319)](https://user-images.githubusercontent.com/84638785/119236866-50cd7100-baff-11eb-9a5a-9eb71bfae41a.png)
Everything you can see (above) I cannot see. I have redownloaded the mod, but it didn't fix the issue. I can't find a solution.

**Comment by SteveKunG** [comment]
This is intended, I feel like my mod need to re-balance and rewrite all of them. I already did this in 1.12.2 and still not pleased.
If you want to discuss about this topic please join my discord. Thank you!
https://discord.gg/6JhEjeY
