### ISSUE TITLE
Crashing before making it to the menu

### ISSUE THREAD

**Issue by AtomizerEmerald** [SteveKunG/MorePlanets#124]
So i had copied all of the files of the latest version of lapititos galacticraft modpack because i wanted to add a few more mods and what not, but for some reason more planets just doesnt want to work with galaxy space?/Galacticraft core,
[crash-2021-08-13_18.30.40-client.txt](https://github.com/SteveKunG/MorePlanets/files/6985579/crash-2021-08-13_18.30.40-client.txt)
![image](https://user-images.githubusercontent.com/88912024/129427050-ef4029d1-49f3-482b-a192-2b529bc4f49e.png)

**Comment by SteveKunG** [comment]
Install JustEnoughIDs should fix IDs limit.
https://www.curseforge.com/minecraft/mc-mods/jeid

**Comment by AtomizerEmerald** [comment]
thanks mate that worked!
