### ISSUE TITLE
Dont know why this showed up please help

### ISSUE THREAD

**Issue by Endertrey** [SteveKunG/MorePlanets#125]
![Iss](https://user-images.githubusercontent.com/89334955/130346818-772d173f-1076-4696-9e64-e0c69e4338f9.PNG)

**Comment by SteveKunG** [comment]
It require build 280 to run the mod.
https://micdoodle8.com/mods/galacticraft/downloads

**Comment by Endertrey** [comment]
it worked thanks mate
