### ISSUE TITLE
Space portal doesn't work.

### ISSUE THREAD

**Issue by LeoonWi** [SteveKunG/MorePlanets#126]
I changed in cfg "B:"Enable Survival Planet Selection"=true", but nothing change. Space portal doesn't work and writes, that "B:"Enable Survival Planet Selection"=false". And I was restarting the game. Maybe I got something wrong?
![2021-08-30_22 58 39](https://user-images.githubusercontent.com/88885732/131397773-4b9315e8-7cf9-48dc-8e5b-5d71907eb57b.png)

**Comment by SteveKunG** [comment]
This should be fixed in the next version, I rewrite Space Portal and its feature to make it more friendly.

**Comment by SteveKunG** [comment]
Please test with More Planets 2.2.2, it should easier to use now :)
