### ISSUE TITLE
Can't open the Space Warp pad's inventory or put the core in

### ISSUE THREAD

**Issue by Joey-Destroyah** [SteveKunG/MorePlanets#129]
Step 1: load up any world with these mods installed on 1.12.2 forge 2855
![Screenshot 2021-09-27 190917](https://user-images.githubusercontent.com/62820134/134997207-00d1885d-6026-42f1-957e-fa70801620a4.png)
Step 2: Build a space warper pad and add space data to it.
Step 3: right click on any block in the pad, and as you will see, nothing. 
![2021-09-27_19 08 07](https://user-images.githubusercontent.com/62820134/134997405-2716aa69-2f41-4928-9226-3d71544518c2.png)
BTW Got the latest beta from curseforge. 
Dont know how to build 1.12.2 mods so if thats the issue, I'm stumped.

**Comment by Joey-Destroyah** [comment]
Shift right click with a core and it will link it to that dimension. Do that to another pad on earth(or any other place), and it will give you "Can only add dimension data once" in the chat dialogue.

**Comment by Hamsterpouch** [comment]
Pretty sure you have to Shift+right click with and empty hand to open the inventory.

**Comment by Joey-Destroyah** [comment]
Thanks!
