### ISSUE TITLE
[Old Version] Dungeons on Kapteyn B, Sirius B, Mercury, Venus and Pluto, Koentus and more

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#13]
Please could you make bosses for each of the dungeons so they can drop the suitable key for the treasure chest, even though we wont be getting a schematic from the chest, people can still get loot from them...

Just creeper bosses for them will be perfect :D

**Comment by MJRLegends** [comment]
Was you able to do anything for this issue? (i say this because of the fixed label)

**Comment by SteveKunG** [comment]
I only added Kapteyn B and Pluto bosses. Some planets doesn't have the treasure room.

**Comment by MJRLegends** [comment]
Ok, i only posted this issue because i was getting reports of players getting confused that dungeons were giving different keys and that

**Comment by SteveKunG** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2358057-more-planets-mod-v-1-3-6-galacticraft-add-on?page=54#c1084
