### ISSUE TITLE
Please Use Branches!

### ISSUE THREAD

**Issue by ETStareak** [SteveKunG/MorePlanets#13]
Hello!Thank you for your work!
You updated many folders to distinguish different verions of your mod,right? But as I know,other developers use the ‘Branches’ to do that,for example, GalactiCraft:https://github.com/micdoodle8/Galacticraft
It could make your github clear and easier for your followers to help you——for example,I can update zh_CN.lang easier.If you think 1.7.10is a big problem,I think you can make another for it only.
Hope everything goes better!

**Comment by SteveKunG** [comment]
OK, I'd separate MC version into each branch.
