### ISSUE TITLE
Incompatible with performant

### ISSUE THREAD

**Issue by 10Maximus10** [SteveKunG/MorePlanets#130]
Crashing if performant is installed.

[latest.log](https://github.com/SteveKunG/MorePlanets/files/7799127/latest.log)

**Comment by SteveKunG** [comment]
Performant is fine in my dev test, but not sure for older released version. After that you should update SteveKunG's Lib to 1.1.11 and More Planets to 2.2.2 after it published.

**Comment by SteveKunG** [comment]
Both mods has been released. Please test and report ASAP :)

**Comment by 10Maximus10** [comment]
Works now thanks.
