### ISSUE TITLE
Game crashes when trying to join server with the Galacticraft modpack installed

### ISSUE THREAD

**Issue by dgrenade16** [SteveKunG/MorePlanets#131]
Error Message: 

> The game crashed whilst batching chunks
Error: java.lang.NullPointerException: Batching chunks
Exit Code: -1

Crash Report:
https://pastebin.com/2FQaZbaP 

- Crashes only happen when I try to join the server. They do not happen when I join a single player world. 
- I have tried replacing FoamFixAPI with FoamFIXAPI-lawful as the crash report states. 
- I am the only one on the server who is experiencing this issue and we are all using the exact same version of the modpack. The server owner tried deleting my player file which worked for a little bit. The crashes started again soon after though. 

Edit: Forgot to mention we are using version 1.12.2 of minecraft, and version 1.1.0 of the modpack

**Comment by SteveKunG** [comment]
Please try with More Planets 2.2.2, I'm not sure what's going on with that. Perhaps could you upload full log?
