### ISSUE TITLE
Server Crashing Upon Start

### ISSUE THREAD

**Issue by xParadox10** [SteveKunG/MorePlanets#132]
Hi, I recently have tried to add the "Extra Planets" mod for Galacticraft to my server. Whenever I do so, even with all the dependencies, it still crashes, and so does my minecraft client when the game tries to load. The file attached is the client log. I can also send the server log if needed.
[latest.log](https://github.com/SteveKunG/MorePlanets/files/7873499/latest.log)

**Comment by SteveKunG** [comment]
Install https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility should fix this.
