### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by ItsFluiids** [SteveKunG/MorePlanets#134]
I'm making a custom mod pack for my friends but this mod says it needs these other mods to work but when I installed them and put them in my mods folder they still say its missing this one mod even though I have them in
See pics below
![Screenshot (1)](https://user-images.githubusercontent.com/97908374/149815947-df8dc10d-8d92-46a8-bc35-c86f76dd158e.png)
![Screenshot (2)](https://user-images.githubusercontent.com/97908374/149815954-b28dc93f-4743-490a-aab9-da26a53ef5b5.png)

**Comment by Joey-Destroyah** [comment]
Copy the install (all of the mods) to your singleplayer mods folder and run the game. Does it display it there?

**Comment by ItsFluiids** [comment]
yes to your question, but also another thing I noticed is that galacticraft core and glacticraft planets use 1.12.2-4.0.2.280 while the micdoodlecore says its only 1.12.2 When I install the 1.12.2.-4.0.2.280 the launcher just crashes before even starting up. so I don't know what it could be that is making this difficult

**Comment by SteveKunG** [comment]
Galacticraft has been merged into one file, you can download it from here so you don't need to use 3 files anymore.
https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy/files/3648807
