### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by Grebanton1234** [SteveKunG/MorePlanets#136]
Im playing with a couple of other mods and my game crashes on start when I add More Planets. I am guessing that there is compatability Issue or something. (I do have SteveKung'sLib installed)

///Update///: So, appearently More Planets needs Mixin Booster (at least it gets activated on start with More Planets or SteveKung'sLib) and that made my game crash before so that is probably the reason for the crashing. But i do not know why it crashes with Mixin Booster.

Here's the crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2(1).jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.19.1_Forge_1.12.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.0.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.23.1_Forge_1.12.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MixinBooter (.mixinbooter-3.2.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.11.jar)
  Backpacked (backpacked-1.4.3-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280(1).jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31(1).jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.17.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:93)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.Chunk
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

(I cut out the system details because those look like they shouldnt be shown online idk)

	| State | ID                       | Version                  | Source                                        | Signature                                |
	|:----- |:------------------------ |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LC    | mcp                      | 9.42                     | minecraft.jar                                 | None                                     |
	| LC    | FML                      | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                    | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy        | 1.0.0                    | minecraft.jar                                 | None                                     |
	| LC    | itemphysic               | 1.4.0                    | minecraft.jar                                 | None                                     |
	| LC    | micdoodlecore            |                          | minecraft.jar                                 | None                                     |
	| LC    | xaerominimap_core        | 1.12.2-1.0               | minecraft.jar                                 | None                                     |
	| LC    | xaeroworldmap_core       | 1.12.2-1.0               | minecraft.jar                                 | None                                     |
	| LC    | mixinbooter              | 3.2                      | minecraft.jar                                 | None                                     |
	| LC    | backpacked               | 1.4.2                    | backpacked-1.4.3-1.12.2.jar                   | None                                     |
	| LC    | foamfixcore              | 7.7.4                    | minecraft.jar                                 | None                                     |
	| LC    | obfuscate                | 0.4.2                    | minecraft.jar                                 | None                                     |
	| LC    | actuallyadditions        | 1.12.2-r152              | ActuallyAdditions-1.12.2-r152.jar             | None                                     |
	| LC    | additional_lights        | 1.12.2-1.2.1             | additional_lights-1.12.2-1.2.1.jar            | None                                     |
	| LC    | aether_legacy            | 1.5.3.2                  | aether-1.12.2-v1.5.3.2.jar                    | None                                     |
	| LC    | crafttweaker             | 4.1.20                   | CraftTweaker2-1.12-4.1.20.673.jar             | None                                     |
	| LC    | jei                      | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LC    | ctm                      | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31(1).jar                  | None                                     |
	| LC    | twilightforest           | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LE    | immersiveengineering     | 0.12-98                  | ImmersiveEngineering-0.12-98.jar              | None                                     |
	| L     | alternatingflux          | 0.12.2-2                 | alternatingflux-0.12.2-2.jar                  | None                                     |
	| L     | appleskin                | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| L     | aquaculture              | 1.6.8                    | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| L     | galacticraftcore         | 4.0.2.280                | GalacticraftCore-1.12.2-4.0.2.280(1).jar      | None                                     |
	| L     | galacticraftplanets      | 4.0.2.280                | Galacticraft-Planets-1.12.2-4.0.2.280(1).jar  | None                                     |
	| L     | asmodeuscore             | 0.0.28                   | AsmodeusCore-1.12.2-0.0.28.jar                | None                                     |
	| L     | quark                    | r1.6-179                 | Quark-r1.6-179.jar                            | None                                     |
	| L     | autoreglib               | 1.3-32                   | AutoRegLib-1.3-32.jar                         | None                                     |
	| L     | bettercaves              | 1.12.2                   | bettercaves-1.12.2-2.0.4.jar                  | None                                     |
	| L     | bibliocraft              | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar             | None                                     |
	| L     | biomesoplenty            | 7.0.1.2445               | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar | None                                     |
	| L     | byg                      | 1.7.1                    | BiomesYouGo1.7.1.jar                          | None                                     |
	| L     | bonsaitrees              | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                    | None                                     |
	| L     | forgelin                 | 1.8.4                    | Forgelin-1.8.4.jar                            | None                                     |
	| L     | bountiful                | 2.2.2                    | Bountiful-2.2.2.jar                           | None                                     |
	| L     | buildcraftlib            | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| L     | buildcraftcore           | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| L     | buildcraftbuilders       | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| L     | buildcrafttransport      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| L     | buildcraftsilicon        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| L     | buildcraftcompat         | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| L     | buildcraftenergy         | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| L     | buildcraftfactory        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| L     | buildcraftrobotics       | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| L     | cdm                      | 0.4.1                    | cdm-0.4.1-mc1.12.2(1).jar                     | None                                     |
	| L     | chameleon                | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| L     | chisel                   | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45(1).jar               | None                                     |
	| L     | chunkanimator            | 1.2                      | ChunkAnimator-MC1.12-1.2.jar                  | None                                     |
	| L     | supermartijn642configlib | 1.0.9                    | supermartijn642configlib-1.0.9-mc1.12.jar     | None                                     |
	| L     | chunkloaders             | 1.1.8                    | chunkloaders-1.1.8-mc1.12.jar                 | None                                     |
	| L     | redstoneflux             | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar       | None                                     |
	| L     | cofhcore                 | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar         | None                                     |
	| L     | cookingforblockheads     | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar         | None                                     |
	| L     | ctgui                    | 1.0.0                    | CraftTweaker2-1.12-4.1.20.673.jar             | None                                     |
	| L     | crafttweakerjei          | 2.0.3                    | CraftTweaker2-1.12-4.1.20.673.jar             | None                                     |
	| L     | creativecore             | 1.10.0                   | CreativeCore_v1.10.69_mc1.12.2.jar            | None                                     |
	| L     | engineersdoors           | 0.9.1                    | engineers_doors-1.12.2-0.9.1.jar              | None                                     |
	| L     | extrabows                | v1.12.2 b13              | extrabows-v1.12.2+b13.jar                     | None                                     |
	| L     | zerocore                 | 1.12.2-0.1.2.9           | zerocore-1.12.2-0.1.2.9.jar                   | None                                     |
	| L     | bigreactors              | 1.12.2-0.4.5.68          | ExtremeReactors-1.12.2-0.4.5.68.jar           | None                                     |
	| L     | farmingforblockheads     | 3.1.28                   | FarmingForBlockheads_1.12.2-3.1.28.jar        | None                                     |
	| L     | foamfix                  | 0.10.14-1.12.2           | foamfix-0.10.14-1.12.2.jar                    | None                                     |
	| L     | cfm                      | 6.3.1                    | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| L     | gc-rpc                   | 2.2.0                    | galacticraft-rpc-2.2.0.jar                    | None                                     |
	| L     | galacticrafttweaker      | 1.12.2-1.0.3             | GalacticraftTweaker-1.12.2-1.0.3.jar          | None                                     |
	| L     | galaxyspace              | 2.0.17                   | GalaxySpace-1.12.2-2.0.17.jar                 | None                                     |
	| L     | immersivepetroleum       | 1.1.10                   | immersivepetroleum-1.12.2-1.1.10.jar          | None                                     |
	| L     | immersivetech            | 1.3.10                   | immersivetech-1.12-1.3.10.jar                 | None                                     |
	| L     | infernalmobs             | 1.7.6                    | InfernalMobs-1.12.2.jar                       | None                                     |
	| L     | inventorypets            | 2.0.15                   | inventorypets-1.12-2.0.15.jar                 | None                                     |
	| L     | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | None                                     |
	| L     | ironchest                | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| L     | dogslie                  | 1.0.2                    | LetSleepingDogsLie-1.12.2-1.0.2.jar           | None                                     |
	| L     | mjrlegendslib            | 1.12.2-1.2.1             | MJRLegendsLib-1.12.2-1.2.1.jar                | None                                     |
	| L     | stevekung's_lib          | 1.1.11                   | SteveKunG's-Lib-1.12.2-1.1.11.jar             | None                                     |
	| L     | moreplanets              | 2.2.2                    | More-Planets-1.12.2-2.2.2-GC280.jar           | None                                     |
	| L     | llibrary                 | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                    | None                                     |
	| L     | mowziesmobs              | 1.5.8                    | mowziesmobs-1.5.8.jar                         | None                                     |
	| L     | multimine                | 1.6.2                    | MultiMine-1.12.2.jar                          | None                                     |
	| L     | multimob                 | 1.0.5                    | multimob-1.0.5.jar                            | None                                     |
	| L     | netherendingores         | 1.12.2-1.4.2             | Netherending-Ores-1.12.2-1.4.2.jar            | None                                     |
	| L     | patchouli                | 1.0-23.6                 | Patchouli-1.0-23.6.jar                        | None                                     |
	| L     | portality                | 1.0-SNAPSHOT             | portality-1.12.2-1.2.3-15.jar                 | None                                     |
	| L     | primitivemobs            | 1.2.3a                   | primitivemobs-1.2.3a.jar                      | None                                     |
	| L     | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| L     | searchablechests         | 1.12-1.5.3               | searchablechests-1.12-1.5.3-3.jar             | None                                     |
	| L     | storagenetwork           | 1.8.0                    | SimpleStorageNetwork-1.12.2-1.8.0.jar         | None                                     |
	| L     | spaceambient             | 0.0.1                    | SpaceAmbient-1.12.2-0.0.1(2).jar              | None                                     |
	| L     | spartanweaponry          | 1.4.0                    | SpartanWeaponry-1.12.2-1.4.0.jar              | None                                     |
	| L     | storagedrawers           | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar               | None                                     |
	| L     | surge                    | 2.0.77                   | Surge-1.12.2-2.0.77.jar                       | None                                     |
	| L     | tesla                    | 1.0.63                   | Tesla-1.12.2-1.0.63.jar                       | None                                     |
	| L     | tetra                    | 0.39.1                   | tetra-1.12.2-0.39.1.jar                       | None                                     |
	| L     | texfix                   | 4.0                      | TexFix V-1.12-4.0.jar                         | None                                     |
	| L     | thesummoner              | 1.0.1-beta               | thesummoner-1.0.1.jar                         | None                                     |
	| L     | travellersboots          | 1.0.4                    | travellersboots-1.12.2-1.0.4.jar              | None                                     |
	| L     | vehicle                  | 0.44.1                   | vehicle-0.44.1-mc1.12.2(2).jar                | None                                     |
	| L     | vc                       | 5.9.16                   | ViesCraft-1.12.2-5.9.16.jar                   | None                                     |
	| L     | xaerominimap             | 21.23.1                  | Xaeros_Minimap_21.23.1_Forge_1.12.jar         | None                                     |
	| L     | xaeroworldmap            | 1.19.1                   | XaerosWorldMap_1.19.1_Forge_1.12.jar          | None                                     |
	| L     | phosphor-lighting        | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar   | None                                     |
	| L     | ropebridge               | 2.0.5                    | RopeBridge-1.12.2-2.2.1.jar                   | None                                     |
	| L     | supertools               | 1.12.2-null              | VanillaPlusTools-1.2.jar                      | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EngineersDoorsLoadingPlugin (engineers_doors-1.12.2-0.9.1.jar)
  nihiltres.engineersdoors.common.asm.EngineersDoorsClassTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2(1).jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.19.1_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.4.0.jar)
  
XaeroMinimapPlugin (Xaeros_Minimap_21.23.1_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MixinBooter (.mixinbooter-3.2.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.11.jar)
  
Backpacked (backpacked-1.4.3-1.12.2.jar)
  com.mrcrayfish.backpacked.asm.BackpackedTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280(1).jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.69_mc1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31(1).jar)
  team.chisel.ctm.client.asm.CTMTransformer
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.17.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 21.10.2 30.0.13025.5005' Renderer: 'Radeon RX 570 Series'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14761 Compatibility Profile Context 21.10.2 30.0.13025.5005
	OpenGlRenderer: Radeon RX 570 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by SteveKunG** [comment]
It is difficult to reproduce an issue, did you still have full log files?

**Comment by meerity** [comment]
I have this problem too

**Comment by SteveKunG** [comment]
Please provide more informations! Comment like this isn't useful.

**Comment by SenoTech** [comment]
Hello everybody,

i have the same issue.

What do we use?
We use a Modpack called "MinecraftTime" but we Modded it our self so we can update the Mods and add more.
If you want i can pn you (over DC Tag:yannick#0040) the Link to the Download of the Modpack we use.

If i add the Mod "More Planets" it bricks the complete install of the Mod and dies on start up and troughs out the error code 1.

What did i try?
Used an older version of the mod
reinstalling modpack and trying it again (seems like a nobrainer)
changed ram settings to 20 GB

I will attach the "censored" latest.log file for you guys (censored if IPs, Names etc. appear, appears as [CENSORED])
[latest.log](https://github.com/SteveKunG/MorePlanets/files/9465931/latest.log)

If you want @SteveKunG just write me over DC so we can exchange faster and resolve the issue.

Thank you all for your time
Regards
Seno

**Comment by SenoTech** [comment]
Ok nvm. i traced back the issue to a old forge version. We use .2854 and it works with the newest version .2860
