### ISSUE TITLE
Chalos Dungeon not generating

### ISSUE THREAD

**Issue by Andrey2345Z** [SteveKunG/MorePlanets#137]
1. I have a issue, I know that at the moment there are three dungeons in More Planets, namely Diona, Nibiru and Chalos, and each of them has bosses! I decided to explore them in creative, and after I looked at the dungeons of Diona and Nibiru, I noticed that the dungeon was not generated in Chalos (to find the dungeons, I used the locator from Galacticraft), I got to the place where the Chalos dungeon should be generated, however it was not there, I even switched to Spectator mode and explored the caves, there was no dungeon anywhere, however, in the Map of the Planets it was shown that there is a dungeon there! I was especially surprised that there are blocks in the inventory of the creative, there is a key and a chest of the Chalos dungeon, there is also a boss that I was able to spawn through the egg, I decided to look into the mod files, and noticed that the files contain data about the Chalos dungeon, and in theory it should generated!

I decided to ask here, who knows why the Chalos dungeon is not generated, maybe it was cut out temporarily, or this is a generation bug! I understand if the question is stupid, I just recently started to study the mod, and I don’t know much about it

2. Second question just out of curiosity, will Koentus and Fronos dungeons be in the future?

Sorry for the grammatical errors, I'm just using a translator

More Planets Version - 2.2.2
Minecraft Version - 1.12.2

**Comment by SteveKunG** [comment]
Cannot reproduce an issue while testing on both development and production. Do you have any world gen mod installed or checking other dungeons on other planets? Not really sure why it broken.

Also Koentus and Fronos won't likely have a Boss Dungeon anytime soon, I feel like it shouldn't have a Boss Dungeon on every planets.

**Comment by Andrey2345Z** [comment]
I don’t know if the Chalos dungeon will appear if I run it without any mods (except for More Planets and Galacticraft itself), but with Galaxy Space and Extra Planets addons it does not appear (I used the compass that is in Galacticraft itself to find it)

**Comment by Andrey2345Z** [comment]
Oh, it's working!
![2022-08-26_18 36 39](https://user-images.githubusercontent.com/99082711/186941874-0a7cd3f2-3505-40ba-a869-4f2200742fcb.png)
