### ISSUE TITLE
Bed Exploding on Fronos and some other problems (Spawnpoint, Space Nether)

### ISSUE THREAD

**Issue by LinuxSquare** [SteveKunG/MorePlanets#140]
Hi there @SteveKunG, me again.

I just wanted to ask, if it's possible to deactivate the bed-explosion on Fronos, when you try to sleep in it, as Fronos is a habitable, earth-like planet with a breathable atmosphere.

Right now, it explodes (like it does in the Nether or End). 
I'd appreciate it, if it would be possible to sleep in a bed in the near future, instead of the cryogenic chamber.

Also, it would be nice, if it's possible to set the spawnpoint on Fronos, without using the "Survival Planet Selection" option. 
(Maybe by sleeping in a bed?)

And I also wanted to note, that if I use the space nether portal on Fronos and I return using the generated portal in the space nether, I end up on Earth again, which is not very useful for me, when the rocket is on Fronos.

Thank you for your time and making this mod free for everyone.

MorePlanets Version:  2.2.2
SteveKunG's Lib Version: 1.1.11
MixinBooter Version: 3.0
MC-Version: 1.12.2

Yours sincerely
LinuxSquare

**Comment by SteveKunG** [comment]
Fixed in 2.2.3. Using bed on Fronos shouldn't explode anymore. Also Space Portal should working properly.
Thanks for playing my mod :).
