### ISSUE TITLE
Unable to get specific box

### ISSUE THREAD

**Issue by wyyyyyyyyyyyyyyyyyyyyyyyyyy** [SteveKunG/MorePlanets#143]
i chick jei and jer but i still cant gain this following two block:Infected Pur lonite Eye Core;Infected Pur lonite Ender core

I checked the Chinese wiki platform (sorry, I don't know if this mod has an English wiki platform), but I can't get any information about them, so I'll ask you for help to answer him.

Don't care about my English level. The above contents are produced by automatic translation software
ขอบคุณนักเขียนที่มีปัญหา ！

**Comment by SteveKunG** [comment]
Sorry for lack of Mod Information.
Ender Core required an Eye of Ender.
Purlonite Eye required a Purlonite Slimeball.
