### ISSUE TITLE
Crash to entry to the nether space MorePlanets 1.12.2-2.2.3-GC280

### ISSUE THREAD

**Issue by RassTass11** [SteveKunG/MorePlanets#145]
When i want to entry to the space nether my minecraft crash, attached crash report and video:

Video: https://drive.google.com/file/d/1cV3dIBYwW-W6UAk59uqUHBWVhjfLs5uF/view?usp=sharing

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (!mixinbooter-4.2.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.2.284.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.18.jar)
  BCModPlugin (backpacks+1.12.2+-+3.5.12.jar)
  SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.2.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/7/22 4:54 PM
Description: Rendering screen

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at asmodeuscore.core.astronomy.gui.screen.NewGuiCelestialSelection.drawCircles(NewGuiCelestialSelection.java:2998)
	at asmodeuscore.core.astronomy.gui.screen.NewGuiCelestialSelection.func_73863_a(NewGuiCelestialSelection.java:2515)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1462)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at asmodeuscore.core.astronomy.gui.screen.NewGuiCelestialSelection.drawCircles(NewGuiCelestialSelection.java:2998)
	at asmodeuscore.core.astronomy.gui.screen.NewGuiCelestialSelection.func_73863_a(NewGuiCelestialSelection.java:2515)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669)

-- Screen render details --
Details:
	Screen name: asmodeuscore.core.astronomy.gui.screen.NewGuiCelestialSelection
	Mouse location: Scaled: (231, 220). Absolute: (926, 138)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['RassTass'/125, l='MpServer', x=-2895.43, y=1202.80, z=2981.00]]
	Chunk stats: MultiplayerChunkCache: 599, 599
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-228,64,104), Chunk: (at 12,4,8 in -15,6; contains blocks -240,0,96 to -225,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 44463 game time, 44463 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 61 total; [EntityChicken['Gallina'/260, l='MpServer', x=-2826.50, y=67.00, z=3004.50], EntityChicken['Gallina'/264, l='MpServer', x=-2816.30, y=72.00, z=2927.12], EntityWolf['Lobo'/265, l='MpServer', x=-2824.02, y=71.00, z=2925.65], EntityBat['Murciélago'/11017, l='MpServer', x=-2879.50, y=41.10, z=2934.50], EntityWolf['Lobo'/267, l='MpServer', x=-2826.12, y=71.00, z=2924.44], EntityZombie['Zombi'/11027, l='MpServer', x=-2855.50, y=13.00, z=3050.50], EntityCreeper['Creeper'/11028, l='MpServer', x=-2966.50, y=42.00, z=2909.50], EntitySkeleton['Esqueleto'/11029, l='MpServer', x=-2872.50, y=52.00, z=3024.50], EntitySkeleton['Esqueleto'/11030, l='MpServer', x=-2872.50, y=52.00, z=3026.50], EntitySkeleton['Esqueleto'/11031, l='MpServer', x=-2870.50, y=52.00, z=3029.50], EntityChicken['Gallina'/280, l='MpServer', x=-2863.55, y=69.00, z=2931.70], EntityChicken['Gallina'/283, l='MpServer', x=-2904.50, y=80.00, z=2975.02], EntityZombie['Zombi'/11040, l='MpServer', x=-2854.50, y=13.00, z=3049.50], EntityChicken['Gallina'/291, l='MpServer', x=-2815.50, y=72.00, z=2928.50], EntityChicken['Gallina'/293, l='MpServer', x=-2816.50, y=71.00, z=2929.50], EntityItem['item.item.egg'/2341, l='MpServer', x=-2867.75, y=68.00, z=2924.13], EntityChicken['Gallina'/294, l='MpServer', x=-2848.37, y=68.00, z=2965.93], EntityChicken['Gallina'/295, l='MpServer', x=-2851.50, y=65.00, z=2974.50], EntityItem['item.item.egg'/2343, l='MpServer', x=-2865.23, y=69.00, z=2932.73], EntityChicken['Gallina'/296, l='MpServer', x=-2851.50, y=65.00, z=2971.50], EntityChicken['Gallina'/297, l='MpServer', x=-2850.50, y=66.00, z=2971.50], EntityItem['item.item.egg'/10799, l='MpServer', x=-2866.27, y=68.00, z=2924.97], EntityItem['item.item.egg'/1902, l='MpServer', x=-2851.36, y=64.00, z=2970.57], EntityItem['item.item.egg'/1916, l='MpServer', x=-2848.46, y=67.00, z=2967.11], EntityItem['item.item.egg'/6527, l='MpServer', x=-2865.04, y=69.00, z=2931.77], GCEntityClientPlayerMP['RassTass'/125, l='MpServer', x=-2895.43, y=1202.80, z=2981.00], EntityPig['Cerdo'/131, l='MpServer', x=-2945.50, y=73.00, z=2982.50], EntityPig['Cerdo'/132, l='MpServer', x=-2945.50, y=74.00, z=2983.50], EntityPig['Cerdo'/133, l='MpServer', x=-2949.51, y=71.00, z=2982.73], EntityPig['Cerdo'/134, l='MpServer', x=-2957.50, y=68.00, z=2978.54], EntityPig['Cerdo'/135, l='MpServer', x=-2957.50, y=68.00, z=2979.55], EntityItem['item.item.egg'/1928, l='MpServer', x=-2852.49, y=64.00, z=2973.61], EntityChicken['Gallina'/141, l='MpServer', x=-2895.68, y=74.00, z=2914.54], EntityPig['Cerdo'/142, l='MpServer', x=-2960.25, y=71.00, z=2981.46], EntityChicken['Gallina'/148, l='MpServer', x=-2892.49, y=72.00, z=2907.63], EntityChicken['Gallina'/149, l='MpServer', x=-2895.50, y=73.00, z=2910.50], EntityChicken['Gallina'/150, l='MpServer', x=-2894.24, y=73.00, z=2910.75], EntityChicken['Gallina'/151, l='MpServer', x=-2865.50, y=69.00, z=2931.50], EntityChicken['Gallina'/152, l='MpServer', x=-2865.42, y=69.00, z=2932.87], EntityChicken['Gallina'/153, l='MpServer', x=-2864.35, y=69.00, z=2933.50], EntityPig['Cerdo'/156, l='MpServer', x=-2942.50, y=76.00, z=2981.50], EntityPig['Cerdo'/157, l='MpServer', x=-2942.50, y=77.00, z=2980.50], EntityChicken['Gallina'/158, l='MpServer', x=-2929.83, y=97.00, z=2993.15], EntityChicken['Gallina'/159, l='MpServer', x=-2934.50, y=97.00, z=2985.17], EntityChicken['Gallina'/160, l='MpServer', x=-2931.50, y=98.00, z=2985.50], EntityChicken['Gallina'/161, l='MpServer', x=-2930.50, y=98.00, z=2988.50], EntityChicken['Gallina'/171, l='MpServer', x=-2868.06, y=68.00, z=2924.20], EntityChicken['Gallina'/172, l='MpServer', x=-2866.50, y=68.00, z=2924.50], EntityChicken['Gallina'/173, l='MpServer', x=-2866.50, y=68.00, z=2923.50], EntityChicken['Gallina'/174, l='MpServer', x=-2862.78, y=69.00, z=2931.27], EntityPig['Cerdo'/211, l='MpServer', x=-2969.50, y=69.00, z=2905.50], EntityPig['Cerdo'/212, l='MpServer', x=-2970.50, y=71.00, z=2908.50], EntityPig['Cerdo'/213, l='MpServer', x=-2972.50, y=70.00, z=2905.50], EntityPig['Cerdo'/214, l='MpServer', x=-2973.88, y=71.00, z=2910.55], EntityPig['Cerdo'/215, l='MpServer', x=-2972.50, y=70.00, z=2906.50], EntityPig['Cerdo'/217, l='MpServer', x=-2970.50, y=70.00, z=2906.50], EntityCelestialFake[''/9433, l='MpServer', x=-2895.50, y=1203.15, z=2981.50], EntityPig['Cerdo'/218, l='MpServer', x=-2975.21, y=71.00, z=2908.09], EntityItem['item.item.egg'/2023, l='MpServer', x=-2935.33, y=97.00, z=2984.35], EntityItem['item.item.egg'/1514, l='MpServer', x=-2863.83, y=69.00, z=2931.97], EntityItem['item.item.egg'/2030, l='MpServer', x=-2898.13, y=79.00, z=2981.31]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_333, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 605679488 bytes (577 MB) / 2296381440 bytes (2190 MB) up to 2296381440 bytes (2190 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2304m
	IntCache: cache: 226, tcache: 801, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version      | Source                                        | Signature                                |
	|:------ |:------------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2860-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2860 | forge-1.12.2-14.23.5.2860-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       | 4.0.2.284    | minecraft.jar                                 | None                                     |
	| LCHIJA | mixinbooter         | 4.2          | minecraft.jar                                 | None                                     |
	| LCHIJA | aether_legacy       | 1.5.3.2      | aether-1.12.2-v1.5.3.2.jar                    | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.284    | Galacticraft-1.12.2-4.0.2.284.jar             | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.284    | Galacticraft-1.12.2-4.0.2.284.jar             | None                                     |
	| LCHIJA | asmodeuscore        | 0.0.30       | AsmodeusCore-1.12.2-0.0.30.jar                | None                                     |
	| LCHIJA | backpacks16840      | 3.5.12       | backpacks+1.12.2+-+3.5.12.jar                 | None                                     |
	| LCHIJA | betternether        | 0.1.8.6      | betternether-0.1.8.6.jar                      | None                                     |
	| LCHIJA | codechickenlib      | 3.2.3.358    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | cwsr                | 3.1.0.0      | Cyan+Warrior+Swords+Mod+3.1.1+(1.12.2).jar    | None                                     |
	| LCHIJA | galaxyspace         | 2.0.18       | GalaxySpace-1.12.2-2.0.18.jar                 | None                                     |
	| LCHIJA | gravestone          | 1.10.3       | gravestone-1.10.3.jar                         | None                                     |
	| LCHIJA | jei                 | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | journeymap          | 1.12.2-5.7.1 | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | stevekung's_lib     | 1.2.0        | SteveKunG's-Lib-1.12.2-1.2.0.jar              | None                                     |
	| LCHIJA | moreplanets         | 2.2.3        | More-Planets-1.12.2-2.2.3-GC280.jar           | None                                     |
	| LCHIJA | nei                 | 2.4.3        | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | spacex              | 1.12.2       | SpaceCraftX-1.2.1.jar                         | fdf52b4949f62c459bc7c8b88b3fc626710d49ff |
	| LCHIJA | twilightforest      | 3.11.1021    | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | zollerngalaxy       | 2.0.44       | ZollernGalaxy-1.12.2-2.0.44.jar               | None                                     |

	Loaded coremods (and transformers): 
MixinBooter (!mixinbooter-4.2.jar)
  
MicdoodlePlugin (Galacticraft-1.12.2-4.0.2.284.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.0.18.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
BCModPlugin (backpacks+1.12.2+-+3.5.12.jar)
  brad16840.core.ClassTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.2.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 472.98' Renderer: 'NVIDIA GeForce GT 640/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GT 640/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.98, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [1.12]+Firewolf+v1.74.zip, Aether b1.7.3 Textures
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 16x Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 472.98
	OpenGlRenderer: NVIDIA GeForce GT 640/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by RassTass11** [comment]
This happened me with the old version of more planets too

**Comment by SteveKunG** [comment]
I can't reproduce an issue, as I've seen in your video there is Space Nether appeared again.
Can you zip your mod pack and upload it to somewhere please? I need to test on my machine.

**Comment by RassTass11** [comment]
https://drive.google.com/file/d/1q0gy5FtqlO8XwWkDvgGerQvnms2T2JFO/view?usp=sharing

Here is the modpack, I think the mod I had a conflict with was "better nether" but I tried it without that mod and the problem persists.
(sorry for my english, i speak spanish xd)

**Comment by SteveKunG** [comment]
I can't reproduce with your modpack, everyting seems fine including no Space Nether appeared on the celestial selection screen.
![image](https://user-images.githubusercontent.com/6128413/178026021-69221f1a-4fee-4087-b4ae-efc8193f919a.png)

**Comment by RassTass11** [comment]
but the space nether yes exist in the mod or not?

Why not appeared you?

**Comment by SteveKunG** [comment]
Space Nether is exist but **used** only for Space Portal. I've hide it from celestial screen because technical reason.

**Comment by RassTass11** [comment]
What space portal, made a portal nether in the space?

Maybe because crash me, but idk why still appeared on celestial screen xd

**Comment by RassTass11** [comment]
Find the space portal but how can i use it?

**Comment by SteveKunG** [comment]
This item, This works only if you choose to play on Survival Planet mode.
![image](https://user-images.githubusercontent.com/6128413/178111643-e9c44c21-8298-4052-b1c2-eb61d5c4b208.png)

**Comment by RassTass11** [comment]
what is the survival planet mode?

**Comment by SteveKunG** [comment]
A mode that let you start survival on other celestial bodies. Message will appeared when you creating a new world.

**Comment by SteveKunG** [comment]
This should be fixed in 2.2.4.

**Comment by RassTass11** [comment]
okey, so i can´t use the portal yet?
