### ISSUE TITLE
Version 2.2.4 reports itself as 2.2.3

### ISSUE THREAD

**Issue by IO2I** [SteveKunG/MorePlanets#146]
After installing moreplanets 2.2.4 it appears as version 2.2.3 in the in-game mod menu
![image](https://user-images.githubusercontent.com/16938966/178622024-3cf6a967-043f-4a8d-a017-7bde164c4ab8.png)
![image](https://user-images.githubusercontent.com/16938966/178622092-11820790-b257-4c72-8291-90e710a171c0.png)

**Comment by SteveKunG** [comment]
Ah, another reason why I hate modding in older versions. This is my fault. I gotta re-uploaded a file.
