### ISSUE TITLE
What about a zh_cn translation?

### ISSUE THREAD

**Issue by Arrokoth486958** [SteveKunG/MorePlanets#148]
My friend (called Anssus) have translated More planets into Chinese (I've also helped), we can contribute the file for this mod.
[MPChinese.zip](https://github.com/SteveKunG/MorePlanets/files/9132036/MPChinese.zip)

**Comment by Arrokoth486958** [comment]
Wait I've forgot Advancement
[MPChinese.zip](https://github.com/SteveKunG/MorePlanets/files/9132193/MPChinese.zip)
s

**Comment by SteveKunG** [comment]
Hey, Thank you for helping translation. But you can use pull request to make changes to my repo. I'd compare to current zh_cn.lang and your file, it seems got broken on multiple lines. Missing `=` symbol. etc.

**Comment by Arrokoth486958** [comment]
Okay, I'll try to fix it. After that, I'll close this Issue.
