### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Bebiezaza** [SteveKunG/MorePlanets#15]
ต้องแปล version เก่าด้วยหรือเปล่า หรือแค่ master

**Comment by Bebiezaza** [comment]
และยัด label ไม่ได้

**Comment by SteveKunG** [comment]
ขอเป็น 1.10+ เพราะเวอร์ชั่นเก่าๆ ไม่ support ละ (สิ้นสุด 1 ม.ค. 2561)

label เพิ่มได้เฉพาะ owner

**Comment by Bebiezaza** [comment]
ok

**Comment by Bebiezaza** [comment]
แล้วที่แปลของ 1.10.2 กับ master อันเดียวกันหรือเปล่า?

**Comment by SteveKunG** [comment]
อันเดียวกัน master เป็นของ 1.11.2

**Comment by Bebiezaza** [comment]
เปิดทิ้งไว้แล้วกัน ใครมีปัญหาอะไรค่อยเอาคำถามมาใส่ที่นี่ (มั้ง)
ถ้ายอมก็...ตามข้างล่าง
English Language only after this (post translation question in this issue)
