### ISSUE TITLE
Crash when joining vanilla hub

### ISSUE THREAD

**Issue by Pythonix756** [SteveKunG/MorePlanets#15]
Hello, I have a mod pack including more planets and whenever I try to join my server's vanilla hub it crashes, I tried other packs they all join cuz they don't have more planets. Can you help me with this. Here is the report: http://pastebin.com/Hxkv5s7S

**Comment by MJRLegends** [comment]
Remove optifine and then try

**Comment by Pythonix756** [comment]
I did, didn't work

**Comment by MJRLegends** [comment]
What is your hub server built out of?

**Comment by Pythonix756** [comment]
Regular 1.7.10 compatible vanilla blocks

**Comment by MJRLegends** [comment]
Ok weird as i have a mod pack including this addon (Space Astronomy) and ive never had this issue with my bungeecord/hub and no one has report a issue like this to me for my pack.

What bungeecord version you using and what jar for the hub?

**Comment by Pythonix756** [comment]
Spigot 1.10 and it's more planets not space astronomy

**Comment by MJRLegends** [comment]
Yeah but more planets is in my pack which is space astronomy.

What bungeecord u using?

**Comment by Pythonix756** [comment]
Idk but it runs from 1.7 to 1.11

**Comment by MJRLegends** [comment]
Try maybe try a 1.7.10 version hub?

**Comment by Pythonix756** [comment]
The hub is compatible with 1.7

**Comment by MJRLegends** [comment]
Please still give it a try as that will answer if its a few other issues that is the cause

**Comment by Pythonix756** [comment]
Alright

**Comment by Pythonix756** [comment]
Nope, crashes

**Comment by MJRLegends** [comment]
Ok what happens if you take your hub off the bungeecord and join it directly without a bungeecord

**Comment by Pythonix756** [comment]
Crashes still, first thing we tried

**Comment by MJRLegends** [comment]
Ok so its to do with your hub not bungeecord. What plugins and what 2.7 jar did you test

**Comment by Pythonix756** [comment]
Spigot and many other plugins. Btw this won't help since the issue is with fronos dirt block and the vanilla dirt block

**Comment by MJRLegends** [comment]
But surely it should be crashing me too then?

**Comment by Pythonix756** [comment]
Idk what's wrong with this

**Comment by MJRLegends** [comment]
But it could be a issue since its not my addon so might be a bug there

**Comment by MJRLegends** [comment]
What happens if you remove all the dirt/grass from your hub world?

**Comment by Pythonix756** [comment]
Did you read the report, it is clearly more planets

**Comment by Pythonix756** [comment]
NO, I wot do that, that obliterates everything

**Comment by MJRLegends** [comment]
@Pythonix756 yeah but if it crashes with the hub then its outside of its intended purpose since its meant for forge so other factors could be the cause

**Comment by MJRLegends** [comment]
Make a copy of your hub world and generate a new world without dirt

**Comment by Pythonix756** [comment]
So what should I do now??? Extra planets doesn't have the systems in more planets and I want these systems

**Comment by MJRLegends** [comment]
see my last few messages :D

**Comment by Pythonix756** [comment]
Tried that, joining a world with no dirt fixed it but I have a whole section made of dirt

**Comment by MJRLegends** [comment]
Then yeah we have confirmed for @SteveKunG that its the dirt having a render conflict

**Comment by Pythonix756** [comment]
Nevermind, I managed to fix the issue but now I need to have a talk with you MJRLegends about Extra Planets. Can you add me on skype or discord?

**Comment by MJRLegends** [comment]
Yeah add me its the same username as this one

**Comment by MJRLegends** [comment]
(On skype)

**Comment by SteveKunG** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2358057-more-planets-mod-v-1-3-5-galacticraft-add-on?page=52#c1058
