### ISSUE TITLE
Crash on start (1.12.2)

### ISSUE THREAD

**Issue by Plastisheep** [SteveKunG/MorePlanets#150]
I can't figure out how to explain this issue so heres the log (I'm using a lot of mods and the log is huge so I have to put it on pastebin):

https://pastebin.com/BTW54iXM

**Comment by Plastisheep** [comment]
I fixed it! Even though forge was accusing this mod, it was actually just forge running out of biome ids. I got a mod to fix that.

**Comment by NNobal76** [comment]
> I fixed it! Even though forge was accusing this mod, it was actually just forge running out of biome ids. I got a mod to fix that.

What mod i need this
