### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by NNobal76** [SteveKunG/MorePlanets#157]
Galacticraft + more planets wouldn't launch, and the config file isn't there so i cant find it. however these config files are here, could i fix the problem by changing something in the config files in the image? also same as extra planets wouldnt launch. all of these are separate launches 
![image](https://user-images.githubusercontent.com/119068030/204026471-401dbc58-e4f7-436f-a943-d25638d81f6f.png)

**Comment by SteveKunG** [comment]
Any crash log?
