### ISSUE TITLE
Fronos not in some part of translation?

### ISSUE THREAD

**Issue by Bebiezaza** [SteveKunG/MorePlanets#16]
ดาว Fronos มีอยู่เป็นกลุ่ม Block กับ Item แต่ไม่มีในกลุ่ม Planet

**Comment by SteveKunG** [comment]
ยังไม่ได้ implement มา หาวิธีแก้ biome gen ได้เมื่อไหร่ก็เพิ่มมาเมื่อนั้น

**Comment by Bebiezaza** [comment]
ok
