### ISSUE TITLE
Poor performance in SteveKunG-Lib's injectWeatherTickEvent

### ISSUE THREAD

**Issue by tie** [SteveKunG/MorePlanets#161]
`adjustPosToNearbyEntity` call in [`injectWeatherTickEvent`](https://github.com/SteveKunG/SteveKunG-Lib/blob/8c40e49463b39fc0f6a77d5039074f410d527384/src/main/java/stevekung/mods/stevekunglib/mixin/WorldServerMixin.java#L22-L37) seems to be loading chunks, and Minecraft keeps unloading them, causing significant performance degradation in the server thread.

https://spark.lucko.me/go5wnUNAJr?hl=26,25,52,50,59

Corresponding event handler: https://github.com/SteveKunG/MorePlanets/blob/1403fa10bd7931ccf1bf10803f8a49c74b69dc27/src/main/java/stevekung/mods/moreplanets/core/event/WorldTickEventHandler.java#L41-L42

cc @TheComputerizer as an interested party since I've encountered this issue in [Dimensional Hopper](https://beta.curseforge.com/minecraft/modpacks/dimension-hopper-the-fall) modpack.

**Comment by SteveKunG** [comment]
You can try experimental build on my discord server.
https://discord.com/channels/356400329086205953/360045643189846019/1079004666190373004

Profiler after fixed.
https://spark.lucko.me/EITFodLr8v?hl=258

https://discord.gg/jdFkqCkd

**Comment by SteveKunG** [comment]
Fixed in 2.3.2.
