### ISSUE TITLE
Crashes on startup with outdated VanillaFix 1.12.2(FIXED)

### ISSUE THREAD

**Issue by captinwill** [SteveKunG/MorePlanets#162]
here is log 

https://pastebin.com/mpQ4EX30

don't know what happend, am using newest version of galacticraft legacy and more planets

**Comment by SteveKunG** [comment]
You didn't install MixinBooter, please try again.

**Comment by captinwill** [comment]
i installed the required items and got this
[crash-2023-04-05_16.49.31-client.txt](https://github.com/SteveKunG/MorePlanets/files/11162990/crash-2023-04-05_16.49.31-client.txt)
and the log is 
https://pastebin.com/Y2Bcww54

**Comment by SteveKunG** [comment]
Most likely outdated VanillaFix, try update to [1.0.10-150](https://www.curseforge.com/minecraft/mc-mods/vanillafix/files/2915154)

**Comment by captinwill** [comment]
worked, thanks!
