### ISSUE TITLE
Game crashes at launcher (logs)

### ISSUE THREAD

**Issue by AceSardonyx** [SteveKunG/MorePlanets#168]
I saw a similar issue to this but there were no logs.
It's probably the same issue, but I cannot find a fix at all :c

[here's a gist of the log](https://gist.github.com/AceSardonyx/c8f2e039c446a903eedac8d8ae3a6f23)

thanks and appriciate! ヾ(•ω•`)o

**Comment by AceSardonyx** [comment]
Ok, I did a little more research and I found that I needed some sort of mixin compatibility.
So I got something for that and it loaded fine.
![image](https://github.com/SteveKunG/MorePlanets/assets/77860646/9bbd6f20-2a5e-4763-898d-b1750443c807)
I got these two that I am going to get, but was the first one what I was supposed to get instead of this?: https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility
Either way, both worked and I will keep the one I got.
Let me know if it's safe to keep both mixin mods, thanks again :)

**Comment by SteveKunG** [comment]
Hey, You'll need mixin booter to get it work. [mixin-0-7-0-8-compatibility](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility) isn't necessary anymore.
https://www.curseforge.com/minecraft/mc-mods/mixin-booter

**Comment by AceSardonyx** [comment]
thanks :)

**Comment by SteveKunG** [comment]
I'm reopening this since I found an issue with latest MixinBooter. :(

**Comment by SteveKunG** [comment]
Fixed by SteveKunG's Lib 1.3.1.
