### ISSUE TITLE
Game crash when i use this mod with forestery

### ISSUE THREAD

**Issue by TreeV2** [SteveKunG/MorePlanets#169]
Hello my game crash when i use moreplanets and forestery together can you somehow fix it?
[latest.log](https://github.com/SteveKunG/MorePlanets/files/12728803/latest.log)
[crash-2023-09-26_16.31.50-client.txt](https://github.com/SteveKunG/MorePlanets/files/12728806/crash-2023-09-26_16.31.50-client.txt)

**Comment by RimakiTaema** [comment]
i Checked on crash analyser so it caused by

Too many Mods are installed, exceeding the game ID limit, causing the game to crash.

if i wrong or right please tell me

**Comment by RimakiTaema** [comment]
so after i tell that what amounts of installed mods??? it analysed by id it reached 4096 so you just installed over 4096 mods right???

**Comment by SteveKunG** [comment]
Install Just Enough IDs should fix game ID limit.
https://www.curseforge.com/minecraft/mc-mods/jeid
