### ISSUE TITLE
Crash On Entering Dark Asteroids

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#17]
See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/683

**Comment by MJRLegends** [comment]
Did you you manage to track down the problem then?

**Comment by MJRLegends** [comment]
Is this fixed in v1.3.7?

**Comment by SteveKunG** [comment]
Might be.... Need testing.

**Comment by MJRLegends** [comment]
Ok thanks, i dont think i can reproduce the problem myself so will probably have to wait to see if someone reports it again to me when i release v1.3.7 in a mod pack update :D
