### ISSUE TITLE
Crash Report - 1.12.x

### ISSUE THREAD

**Issue by CDAGaming** [SteveKunG/MorePlanets#17]
Crash Occured a few seconds after loading the Tier 6 Planet:

[Hastebin Link](https://hastebin.com/sipujuqiqe.scala)

@SteveKunG is being pinged for awareness but thank you for the great mod :)

**Comment by SteveKunG** [comment]
You need to include moreplanets_at.cfg into your workspace before setting up.

**Comment by CDAGaming** [comment]
It is, The IDE I'm using, IntelliJ, automatically detected it. All Dependencies were also added correctly too

**Comment by CDAGaming** [comment]
@SteveKunG The original error here is no more but There is one other error occuring on my server whenever i go to either planet: https://hastebin.com/anajuterom.css

**Comment by SteveKunG** [comment]
On the server side I didn't get this error log.

**Comment by CDAGaming** [comment]
Odd, as for me the only time I get it is when i enter into one of the 2 planets. If i load again, since im already in the planet, it doesn't crash.

**Comment by SteveKunG** [comment]
Yeah, I've found it in my tests. Will push commit to fix this, Thanks!

**Comment by CDAGaming** [comment]
Will Test once I'm home to see if it's fixed but Thanks :)
