### ISSUE TITLE
[Old Version][1.7.10] Missing localisation of a spawn egg name

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#19]
![](https://i.gyazo.com/3bb03e5f1a9b9b972a7dc676d056b806.png)

**Comment by MJRLegends** [comment]
Language used: en_US

**Comment by MJRLegends** [comment]
Another missing localisation its not major but thought i point it out

![](https://i.gyazo.com/b7c28722f493a313d30ce938460544d7.png)

**Comment by SteveKunG** [comment]
Fixed in the next version.

**Comment by MJRLegends** [comment]
I can confirm its fixed, thanks
