### ISSUE TITLE
Already decorating crash

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#2]
I seems that me and other players of my mod pack are getting this crash, it seems this crash is happening on SiriusB and Fronos

**Crash Log 1 From another user of my mod pack**

This is a player that reported this to me https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/275

**Crash log/Log from my server**

And this is from my server:
Crash log http://pastebin.com/ukuB5n4M
Here is the full log for the server because it holds some errors coming from forge related to this crash 
[2016-04-29-6.txt](https://github.com/SteveKunG/MorePlanets/files/243546/2016-04-29-6.txt)

**Comment by SteveKunG** [comment]
It's happen in the old version of Cauldron??

**Comment by MJRLegends** [comment]
Im really not sure because if i downgrade the version of kCauldron a load of other crashes happen that have been fixed in the latest versions of kCauldron

**Comment by MJRLegends** [comment]
I have tried posting this issue on there issue tracker before but they wasnt really that helpful at all with looking in to the issue

**Comment by MJRLegends** [comment]
A fix that seems to work for this issue is to: try changing the option "load chunk on request" to false in cauldron.yml
