### ISSUE TITLE
[Old Version][1.7.10] Pluto Dungeon Bugs

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#20]
The key that is dropped is a Polongnius key, its not a major issue as it still works in the Pluto treasure chest but could confuse players since it doesn't say Pluto
![](https://i.gyazo.com/82d6f2ff2caef7133df33e4eb2d76538.png)

Also when looking in the chest i got a Tier 8 schematic, which means Tier 6 and 7 are being skipped
![](https://i.gyazo.com/35b0ea99e3c76d0021dd4b7fd4a3932b.png)

**Comment by MJRLegends** [comment]
Also the Kapteyn B has the Tier 8 schematic, this isnt a bug but it means that there is two planets that you can get the Tier 8 schematic from, I'd thought i would bring it up just in case this wasn't your aim with the Kapteyn B dungeon

**Comment by MJRLegends** [comment]
@SteveKunG Out of all my current posted bugs, this one is the major important bug :P

**Comment by SteveKunG** [comment]
Fixed in the next version. Remove planet name from Dungeon Key.

**Comment by MJRLegends** [comment]
Ok what about the Tier 8 schematic in the treasure chest loot

**Comment by SteveKunG** [comment]
It changed to Tier 6 Schematic.

**Comment by MJRLegends** [comment]
Ok sounds good thanks is there a eta on the update release?

**Comment by SteveKunG** [comment]
17:15 PM in Thai.

**Comment by MJRLegends** [comment]
Perfect thanks

**Comment by SteveKunG** [comment]
http://www.mediafire.com/file/kq9j691f9l9eiut/More-Planets-1.7.10-1.3.8.jar

**Comment by MJRLegends** [comment]
Thanks, I'll let you know if i find any more bugs

**Comment by MJRLegends** [comment]
I can confirm its fixed, thanks
