### ISSUE TITLE
[Old Version][1.7.10] Iridium Ingot Conflict with Advanced Solar Panels Mod

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#22]
When the Advanced Solar Panels Mod is installed the recipes for converting Iridium Ore from More Planets to Iridium Ingot's it defaults to the Advanced Solar Panels Mod version which doesn't work in the Galacticraft Compressor recipe.

You should be able to fix this by making the Galacticraft Compressor recipe use ore dictionary entry for the Iridium Ingot which should allow the Advanced Solar Panels Mod version and the more planets version to be picked up in the Galacticraft Compressor recipe

**Comment by MJRLegends** [comment]
I believe the Galacticraft Compressor recipe that has the conflict is the converting Iridium Ingot's to Compressed Iridium

**Comment by SteveKunG** [comment]
Fixed in the next version.
Ore dictionary name : "ingotIridium"

**Comment by MJRLegends** [comment]
I can confirm its fixed, thanks
