### ISSUE TITLE
[SpongeForge - 1.12.2] Dimensions being Unloaded and Reloaded Loop

### ISSUE THREAD

**Issue by CDAGaming** [SteveKunG/MorePlanets#22]
On newest Version of MorePlanets, after PostInitialization, dimensions -2544 and -2542 will constantly unload and reload over and over. I'll try to get a log for this when i can.

**Comment by CDAGaming** [comment]
Edit: When trying to stop the server, it hangs on both dimensions with a log like this:
`[Server thread/WARN] [Sponge]: Attempt made to initialize dimension id -2544 which isn't registered!, falling back to overworld.
`

**Comment by SteveKunG** [comment]
Is this happen only with my mod? Do you test with Extra Planets yet?

**Comment by CDAGaming** [comment]
Yes, as without your mod, none of the other dimensions go into a loop. (Tested last night with and without More Planets and MorePlanets Extras)

**Comment by MJRLegends** [comment]
This is a weird issue... even more if its just MorePlanets and them two dimensions

**Comment by SteveKunG** [comment]
Possible caused by lightning spawn? The dimension -2542 is Diona, -2544 is Nibiru.

I will temporary disabled lightning spawn handler and build Dev file for testing.

**Comment by CDAGaming** [comment]
@SteveKunG Unfortunatly, this issue is still present on your newest update to MorePlanets

**Comment by SteveKunG** [comment]
This should fix by this (Maybe?) : https://github.com/SteveKunG/MorePlanets/commit/e6d5f1a9ded55c6bf773a87ed19eed377e84874c

I will re-open this If it still an issue in version 2.1.0.
