### ISSUE TITLE
[1.12.2] Galacticraft 4.0.1.152 crashes - getTranclucentArmorModel

### ISSUE THREAD

**Issue by wamc2017** [SteveKunG/MorePlanets#24]
### Description of Issue
Game crashes during start, if Galacticraft is updated to 4.0.1.152 (4.0.151 works fine... :))

### Steps to Reproduce Issue
1. Update to 4.0.1.152
2. Start the game

**Crash log/Log:**
https://pastebin.com/TVJtdiUm

**Version of Mod using:** 2.0.13-GC150

**Comment by RyanHakurei** [comment]
I can confirm it crashes on 153 as well. Strangely enough it only crashes my client, my server is able to start just fine with 2.0.13-GC150 and Galacticraft 153

**Comment by SteveKunG** [comment]
Only server side work fine, I did recommend use GC build 151 for temporary.

Edit : Maybe I will pushed out a new version if possible.

**Comment by RyanHakurei** [comment]
@wamc2017 Can you or @SteveKunG provide me a copy of GC 151 (GC Core, GC Planets, and Micdoodle8 core) as the website 404s when I try to download the 151 builds.

**Comment by SteveKunG** [comment]
https://ci.micdoodle8.com/job/Galacticraft-1.12/151/

**Comment by SteveKunG** [comment]
Fixed in https://github.com/SteveKunG/MorePlanets/commit/0b6ce698a78fbc266a305dfd71f1bc211c635d11
