### ISSUE TITLE
Already decorating, Crash on KapteynB

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#24]
Crash log: http://pastebin.com/CJjBN2hy

Server is running: Thermos:1.7.10-1614.57
More Planets Version: Latest (v1.3.8)

I have the fix i found for this issue changed but isn't stopping this crash (Issue this fix was posted in #2)
![](https://i.gyazo.com/d22c8eaf81249bdc179df40eb5bf181a.png)

The player was just generating new chunks...

**Comment by MJRLegends** [comment]
From what i can see from the crash log its to do with the FrozenWater generating

**Comment by SteveKunG** [comment]
Fixed in the next version. Thanks.

**Comment by MJRLegends** [comment]
@SteveKunG Hey just wondering, is there a eta on the next version. I only ask as im working on a mod pack update

**Comment by MJRLegends** [comment]
@SteveKunG Hey just wondering, is there a eta on the next version. I only ask as im working on a mod pack update
