### ISSUE TITLE
(1.7.10) [MP-1.3.6+] Client crash

### ISSUE THREAD

**Issue by Cronosus** [SteveKunG/MorePlanets#25]
Client crashing, when i open map and clicking on planets
http://pastebin.com/MSUyiamD

edit: ill try now newest version, miss update
edit2: caused on 1.3.8 too

**Comment by MJRLegends** [comment]
I think your issue is with galaxyspace, as the crash log shows the code below

```
-- Screen render details --
Details:
    Screen name: galaxyspace.SolarSystem.core.coremod.gui.screen.GSGuiCelestialSelection
    Mouse location: Scaled: (439, 228). Absolute: (878, 560)
    Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2
```

**Comment by Cronosus** [comment]
hmm
i thnk ist something with compatibility, its caused only when i have GS and MP together in pack.
http://pastebin.com/yYve0ka6

**Comment by MJRLegends** [comment]
Yeah its probably because galaxy space has features and they dont handle well with more planets, planets
