### ISSUE TITLE
Block Sound Event crash

### ISSUE THREAD

**Issue by plenet10** [SteveKunG/MorePlanets#26]
I broke tall grass and it killed the client. just a note it could be something to do with other mods because i have more than 500 of them running.
if you need anything just say and i will try to add it for you.
[crash-2018-03-25_20.48.56-client.txt](https://github.com/SteveKunG/MorePlanets/files/1845712/crash-2018-03-25_20.48.56-client.txt)

**Comment by SteveKunG** [comment]
I can't reproduce in my tests. Also Koentus Block still unobtainable in survival except Creative Mode.

**Comment by SteveKunG** [comment]
Due to remove metadata from block, this should be fixed.
