### ISSUE TITLE
[1.7.10] GUI Elements, Oxygen/Thermal bar do not show on Mercury

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#27]
See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/770

cc: @radfast (Not sure if its something on GC end causing it :D )

**Comment by SteveKunG** [comment]
Its my mod bug. Not GC.
Also fixed in the next version.

**Comment by MJRLegends** [comment]
Thanks i can confirm its fixed :D
