### ISSUE TITLE
Space station type conflict at -29 home planet id

### ISSUE THREAD

**Issue by MPeti1** [SteveKunG/MorePlanets#27]
If I add MorePlanets to the mods, the game will crash with the following message:
`java.lang.RuntimeException: Two space station types registered with the same home planet ID: -29
	at micdoodle8.mods.galacticraft.api.GalacticraftRegistry.registerSpaceStation(GalacticraftRegistry.java:140)
	at stevekung.mods.moreplanets.core.MorePlanetsCore.postInit(MorePlanetsCore.java:333)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
... `

**Comment by MPeti1** [comment]
Had a look on the mod's code, and it seems I've found a solution. In the mod's config file I found you have a setting `B:"Enable Mars Space Station"`, I've set it to false and it works now. Could you check in the beginning of `post init` if the id of the planets are already used by other mods? You could just send a message with the crash (throw an exception with a custom cause) or you could make a screen like when Forge finds mod version conflicts (like [this](https://i.ytimg.com/vi/2NaLzySvmH8/hqdefault.jpg)) if one of the id's are already used

**Comment by danieru-desu** [comment]
The problem is that whatever number you put into  `I:dimensionIDMars=` it's still crashing.
Full crash report if it helps somehow https://pastebin.com/p8dsRDet.

**Comment by MPeti1** [comment]
@SteveKunG sorry, was the problem fixed?

**Comment by BlesseNtumble** [comment]
Disable Mars Space station in configs More Planets or Galaxy Space.
