### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by SheroxGG** [SteveKunG/MorePlanets#29]
I would like to add galacticraft to my modpack folder but it crashes my game, could you please help me fixing it? Thanks. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.1.0-alpha-snapshot-universal.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 5/17/18 11:30 PM
Description: Initializing game

java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/client/renderer/EntityRenderer.func_78472_g(F)V @91: invokestatic
  Reason:
    Type 'net/minecraft/world/World' (current frame, stack[0]) is not assignable to 'net/minecraft/client/multiplayer/WorldClient'
  Current Frame:
    bci: @91
    flags: { }
    locals: { 'net/minecraft/client/renderer/EntityRenderer', float, 'net/minecraft/world/World' }
    stack: { 'net/minecraft/world/World' }
  Bytecode:
    0x0000000: 2ab4 04a1 9904 152a b400 e3b4 0224 1304
    0x0000010: a4b6 022b 2ab4 00e3 b401 d64d 2cc6 03fc
    0x0000020: b804 a799 0037 2c2a b404 9f2a b401 0d2a
    0x0000030: b400 e3b4 01c0 b204 aab6 0435 23b8 04b0
    0x0000040: 9900 1a2a b400 fdb6 04b3 2a03 b504 a12a
    0x0000050: b400 e3b4 0224 b602 bfb1 2cb8 04b9 4625
    0x0000060: 1303 fe6a 1301 ad62 3804 0336 0515 0511
    0x0000070: 0100 a203 912c b404 bdb6 04c3 1505 1010
    0x0000080: 6c30 1704 6a38 062c b404 bdb6 04c3 1505
    0x0000090: 1010 7030 2ab4 049f 1301 e86a 1302 dd62
    0x00000a0: 6a38 072c b604 c69e 0012 2cb4 04bd b604
    0x00000b0: c315 0510 106c 3038 0617 0625 1304 c76a
    0x00000c0: 1304 c862 6a38 0817 0625 1304 c76a 1304
    0x00000d0: c862 6a38 0917 0717 0713 01a8 6a13 04c9
    0x00000e0: 6213 01a8 6a13 04c9 626a 380a 1707 1707
    0x00000f0: 1707 6a13 01a8 6a13 04c9 626a 380b 1708
    0x0000100: 1707 6238 0c17 0917 0a62 380d 1706 170b
    0x0000110: 6238 0e17 0c13 04ca 6a13 04cb 6238 0c17
    0x0000120: 0d13 04ca 6a13 04cb 6238 0d17 0e13 04ca
    0x0000130: 6a13 04cb 6238 0e2a b401 f40b 959e 004e
    0x0000140: 2ab4 01f6 2ab4 01f4 2ab4 01f6 6623 6a62
    0x0000150: 380f 170c 0c17 0f66 6a17 0c13 04cc 6a17
    0x0000160: 0f6a 6238 0c17 0d0c 170f 666a 170d 1301
    0x0000170: a86a 170f 6a62 380d 170e 0c17 0f66 6a17
    0x0000180: 0e13 01a8 6a17 0f6a 6238 0e2c b404 bdb6
    0x0000190: 04d0 b604 d504 a000 2713 04d6 1707 1304
    0x00001a0: d76a 6238 0c13 04d8 170a 1304 d76a 6238
    0x00001b0: 0d13 04d9 170b 1304 d76a 6238 0eb2 04dc
    0x00001c0: b601 5199 005b 06bc 0659 0317 0c51 5904
    0x00001d0: 170d 5159 0517 0e51 3a0f 2cb4 04bd b204
    0x00001e0: dc08 bd00 0459 0323 b803 2253 5904 25b8
    0x00001f0: 0322 5359 0517 06b8 0322 5359 0617 07b8
    0x0000200: 0322 5359 0719 0f53 b804 df57 190f 0330
    0x0000210: 380c 190f 0430 380d 190f 0530 380e 170c
    0x0000220: 0b0c b801 e738 0c17 0d0b 0cb8 01e7 380d
    0x0000230: 170e 0b0c b801 e738 0e2a b400 e3b4 01c0
    0x0000240: b204 aab6 0435 9900 6d2a 2ab4 00e3 b401
    0x0000250: c023 b604 e338 0f0c 170c 6e38 1017 100c
    0x0000260: 170d 6e95 9e00 090c 170d 6e38 1017 100c
    0x0000270: 170e 6e95 9e00 090c 170e 6e38 1017 0c0c
    0x0000280: 170f 666a 170c 1710 6a17 0f6a 6238 0c17
    0x0000290: 0d0c 170f 666a 170d 1710 6a17 0f6a 6238
    0x00002a0: 0d17 0e0c 170f 666a 170e 1710 6a17 0f6a
    0x00002b0: 6238 0e17 0c0c 959e 0006 0c38 0c17 0d0c
    0x00002c0: 959e 0006 0c38 0d17 0e0c 959e 0006 0c38
    0x00002d0: 0e2a b400 e3b4 019f b404 e638 0f0c 170c
    0x00002e0: 6638 100c 170d 6638 110c 170e 6638 120c
    0x00002f0: 1710 1710 6a17 106a 1710 6a66 3810 0c17
    0x0000300: 1117 116a 1711 6a17 116a 6638 110c 1712
    0x0000310: 1712 6a17 126a 1712 6a66 3812 170c 0c17
    0x0000320: 0f66 6a17 1017 0f6a 6238 0c17 0d0c 170f
    0x0000330: 666a 1711 170f 6a62 380d 170e 0c17 0f66
    0x0000340: 6a17 1217 0f6a 6238 0e17 0c13 04ca 6a13
    0x0000350: 04cb 6238 0c17 0d13 04ca 6a13 04cb 6238
    0x0000360: 0d17 0e13 04ca 6a13 04cb 6238 0e17 0c0c
    0x0000370: 959e 0006 0c38 0c17 0d0c 959e 0006 0c38
    0x0000380: 0d17 0e0c 959e 0006 0c38 0e17 0c0b 969c
    0x0000390: 0006 0b38 0c17 0d0b 969c 0006 0b38 0d17
    0x00003a0: 0e0b 969c 0006 0b38 0e17 0c2c b804 ea6a
    0x00003b0: 380c 170d 2cb8 04ed 6a38 0d17 0e2c b804
    0x00003c0: f06a 380e 1100 ff36 1317 0c13 04f1 6a8b
    0x00003d0: 3614 170d 1304 f16a 8b36 1517 0e13 04f1
    0x00003e0: 6a8b 3616 2ab4 010d 1505 1304 f215 1410
    0x00003f0: 1078 8015 1510 0878 8015 1680 4f84 0501
    0x0000400: a7fc 6d2a b400 fdb6 04b3 2a03 b504 a12a
    0x0000410: b400 e3b4 0224 b602 bfb1               
  Stackmap Table:
    append_frame(@90,Object[#1205])
    append_frame(@109,Float,Float,Integer)
    append_frame(@185,Float,Float)
    full_frame(@395,{Object[#2],Float,Object[#1205],Float,Float,Integer,Float,Float,Float,Float,Float,Float,Float,Float,Float},{})
    same_frame(@445)
    same_frame_extended(@542)
    append_frame(@621,Float,Float)
    same_frame(@637)
    chop_frame(@691,2)
    same_frame(@701)
    same_frame(@711)
    same_frame(@721)
    full_frame(@887,{Object[#2],Float,Object[#1205],Float,Float,Integer,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float,Float},{})
    same_frame(@897)
    same_frame(@907)
    same_frame(@917)
    same_frame(@927)
    same_frame(@937)
    full_frame(@1027,{Object[#2],Float,Object[#1205],Float,Float},{})
    chop_frame(@1049,3)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:522)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:522)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 984710784 bytes (939 MB) / 1476395008 bytes (1408 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 Optifine OptiFine_1.12.2_HD_U_D2 64 mods loaded, 64 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                | Source                                             | Signature                                |
	|:----- |:--------------------- |:---------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| U     | minecraft             | 1.12.2                 | minecraft.jar                                      | None                                     |
	| U     | mcp                   | 9.42                   | minecraft.jar                                      | None                                     |
	| U     | FML                   | 8.0.99.99              | forge-1.12.2-14.23.3.2655.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge                 | 14.23.3.2655           | forge-1.12.2-14.23.3.2655.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | micdoodlecore         |                        | minecraft.jar                                      | None                                     |
	| U     | alib                  | 1.0.0                  | A-Lib-1.12.2.jar                                   | None                                     |
	| U     | aether                | 1.12.2-1.0.4           | aether_ii-1.12.2-1.0.4.jar                         | None                                     |
	| U     | alchemistry           | 0.7.2                  | alchemistry-0.7.2.jar                              | None                                     |
	| U     | arcademod             | 2.1.1                  | arcademod-2.1.1-1.12.2.jar                         | None                                     |
	| U     | armorchroma           | 1.3                    | Armor-Chroma-Mod-1.12.2.jar                        | None                                     |
	| U     | baubles               | 1.5.2                  | Baubles-Mod-1.12.2.jar                             | None                                     |
	| U     | blockdrops            | 1.3.0                  | Block-Drops-Mod-1.12.jar                           | None                                     |
	| U     | buildcraftbuilders    | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| U     | buildcraftcore        | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| U     | buildcraftenergy      | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| U     | buildcraftfactory     | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| U     | buildcraftlib         | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| U     | buildcraftrobotics    | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| U     | buildcraftsilicon     | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| U     | buildcrafttransport   | 7.99.14                | BuildCraft-Mod-1.12.2.jar                          | None                                     |
	| U     | cavern                | 2.1.5                  | Cavern_1.12.2-v2.1.5.jar                           | None                                     |
	| U     | chococraft            | 0.9.1.52               | ChocoCraft-Mod-1.12.1.jar                          | None                                     |
	| U     | codechickenlib        | 3.1.6.339              | CodeChickenLib-1.12.2.jar                          | None                                     |
	| U     | cosmeticarmorreworked | 1.12.2-v1              | Cosmetic-Armor-Reworked-Mod-1.12.2.jar             | None                                     |
	| U     | deepmoblearning       | 1.12.2-1.2.0           | Deep-Mob-Learning-Mod-1.12.2.jar                   | None                                     |
	| U     | enchdesc              | 1.1.8                  | Enchantment-Descriptions-Mod-1.12.2.jar            | None                                     |
	| U     | extraplanets          | 1.12.2-0.1.5           | Extra-Planets-Mod-1.12.2.jar                       | None                                     |
	| U     | extrautils2           | 1.0                    | Extra-Utilities-Mod-1.12.1.jar                     | None                                     |
	| U     | forgelin              | 1.6.0                  | Forgelin-1.6.0.jar                                 | None                                     |
	| U     | galacticraftcore      | 4.0.1.121              | Galacticraft-Mod-1.12.2.jar                        | None                                     |
	| U     | galacticraftplanets   | 4.0.1.121              | Galacticraft-Planets-Mod-1.12.2.jar                | None                                     |
	| U     | waila                 | 1.8.24                 | Hwyla-1.8.24-B39_1.12.jar                          | None                                     |
	| U     | ic2                   | 2.8.16-ex112           | Industrial-Craft-2-Mod-Experimental-1.12.1.jar     | None                                     |
	| U     | inventorygenerators   | 1.1.1                  | Inventory-Generators-Mod-1.12.2.jar                | None                                     |
	| U     | ironchest             | 1.12.2-7.0.40.824      | Iron-Chests-Mod-1.12.2.jar                         | None                                     |
	| U     | jei                   | 4.9.1.168              | jei_1.12.2-4.9.1.168.jar                           | None                                     |
	| U     | cjcm                  | 1.0                    | Jumping-Castle-Mod-1.12.2.jar                      | None                                     |
	| U     | mystic                | 0.7.0                  | Kether-Mod-1.12.2.jar                              | None                                     |
	| U     | kjlib                 | 1.0.4                  | kjlib-1.0.4.jar                                    | None                                     |
	| U     | mantle                | 1.12-1.3.2.24          | Mantle-1.12-1.3.2.24.jar                           | None                                     |
	| U     | mirror                | 1.12.2-0.1.0-0         | Mirror-Mod-1.12.2.jar                              | None                                     |
	| U     | mjrlegendslib         | 1.12.2-1.0.5           | MJRLegendsLib-1.12.2.jar                           | None                                     |
	| U     | mocreatures           | 12.0.3                 | Mo-Creatures-Mod-1.12.2.jar                        | None                                     |
	| U     | moartinkers           | 0.5.4                  | Moar-Tinkers-Mod-1.12.2.jar                        | None                                     |
	| U     | moreplanets           | 2.0.11                 | More-Planets-Mod-1.12.2.jar                        | None                                     |
	| U     | recipehandler         | 0.9                    | No-More-Recipe-Conflict-Mod-1.12.1.jar             | None                                     |
	| U     | nei                   | 2.4.1                  | Not-Enough-Items-1.12.2-Recommended.jar            | None                                     |
	| U     | orbis_api             | 1.12.2-1.1             | orbis_api-1.12.2-1.1.jar                           | None                                     |
	| U     | planetprogression     | 1.12.2-0.1.5           | Planet-Progression-Mod-1.12.2.jar                  | None                                     |
	| U     | plustic               | 6.4.0.0                | plustic-6.4.0.0.jar                                | None                                     |
	| U     | preston               | 0.3.3                  | Preston-Mod-1.12.2.jar                             | None                                     |
	| U     | redstoneflux          | 2.0.1                  | RedstoneFlux-1.12-2.0.1.2-universal.jar            | None                                     |
	| U     | lteleporters          | 1.12.2-3.0.2           | Simple-Teleporters-Mod-1.12.2.jar                  | None                                     |
	| U     | thaumcraft            | 6.1.BETA12             | Thaumcraft-Mod-1.12.2.jar                          | None                                     |
	| U     | thaumicjei            | 1.2.1                  | Thaumic-JEI-Mod-1.12.2.jar                         | None                                     |
	| U     | thebetweenlands       | 3.1.0-alpha-snapshot   | TheBetweenlands-3.1.0-alpha-snapshot-universal.jar | None                                     |
	| U     | tinker_io             | release 2.5.5e         | tinker_io-1.12-release 2.5.5e.jar                  | None                                     |
	| U     | tconstruct            | 1.12.2-2.9.0.55        | Tinkers-Construct-Mod-1.12.2.jar                   | None                                     |
	| U     | tinkersjei            | 1.0                    | Tinkers-JEI-Mod-1.12.2.jar                         | None                                     |
	| U     | tinkertoolleveling    | 1.12-1.0.3.DEV.56fac4f | Tinkers-Tool-Leveling-Mod-1.12.2.jar               | None                                     |
	| U     | tropicraft            | 7.1.0.50               | Tropicraft-Mod-1.12.2.jar                          | None                                     |
	| U     | twilightforest        | 3.0.0                  | Twilight-Forest-Mod-1.12.2.jar                     | None                                     |
	| U     | wailaharvestability   | 1.1.11                 | Waila-Harvestability-Mod-1.12.jar                  | None                                     |
	| U     | xaerominimap          | 1.15                   | Xaeros_Minimap_1.15_Forge_1.12.jar                 | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.1.0-alpha-snapshot-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 397.64' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2655
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 397.64, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_D2
	OptiFine Build: 20180430-132249
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 397.64
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by MJRLegends** [comment]
Looks like you havent downloaded the mods for official sources...

download from CurseForge and mod devs own websites only!!! 

I can tell this from the file names and no Signature for any mods that i own have them.

Checkout http://stopmodreposts.org/ as people shouldnt be allowed to repost mods on scam sites its illegal posting, And please download the browser plugins found near the bottom of http://stopmodreposts.org/get-involved/ to make sure your not helping these people!! #StopModReposts

**Comment by SheroxGG** [comment]
I am really sorry, I didnt know that was good, I tought that they had permission. Really sorry, I tried with the original mods from curse and it doesnt work neither, any idea?

**Comment by SheroxGG** [comment]
Wow the real mods just fixed my minecraft, Thanks!! You helped me with some other crashes!!

**Comment by SteveKunG** [comment]
@MJRLegends Thanks for your help while I'm working on my mod :)
