### ISSUE TITLE
Crash on Venus with plants/crops

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#3]
Crash log from server http://pastebin.com/ACwqH574

Im not really sure what he was mining but he was on venus so im guessing its the plants that are located on there?

Edit: after having a look at the log i can see its the corn from fronos

Let me know if you need any more information

**Comment by MJRLegends** [comment]
@SteveKunG Have you had a chance to take a look at this issue yet

**Comment by SteveKunG** [comment]
OK, I'll take a look at this issue. Sorry I didn't looking at my repository for a long time....

**Comment by SteveKunG** [comment]
Can you provide me about step to reproduce the bug?

**Comment by MJRLegends** [comment]
I can try but its been a long time since and a player reported it to me on my server

**Comment by SteveKunG** [comment]
OK. Please try this version.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2358057-more-planets-mod-v-1-3-1-galacticraft-add-on?page=48#c972

**Comment by MJRLegends** [comment]
@SteveKunG ok but what did you change in that version

**Comment by SteveKunG** [comment]
Try to fix this issue and #6

**Comment by MJRLegends** [comment]
@SteveKunG ok any chance you could create a basic Jupiter to fix the issue we talked about via skype or would putting it on its own world provider and that help?

**Comment by MJRLegends** [comment]
@SteveKunG also any chance you can add some basic textures for the missing ones?
