### ISSUE TITLE
[1.12.2] Crash and severe x-raying and possible world curruption

### ISSUE THREAD

**Issue by DWX12** [SteveKunG/MorePlanets#30]
Working on creating a space themed mod pack and visited Niburu. Everything this is fine until I visit the "end portal". If I try to place the vein eyes, sometimes they fail and sometimes they work; however, upon doing so x-raying starts occurring and more along the lines of blocks blinking in and out rather than just simply seeing through blocks. I have VanillaFix installed so I'm able to keep playing, which I'm sure I would have crashed straight away upon attempting to place vein eyes into the portal frame. No portal ever showed up either.

Also would like to know if that portal takes you to the End or where it leads if not.

Figured I'd send you the physical crash report and a hastebin link with it for your viewing pleasure.

[crash-2018-06-11_21.51.09-server.txt](https://github.com/SteveKunG/MorePlanets/files/2092593/crash-2018-06-11_21.51.09-server.txt)

https://hastebin.com/asazepiweg.rb

**Comment by SteveKunG** [comment]
OK, I've fixed in development. New More Planets build will release in couple days.

**Comment by DWX12** [comment]
Great, I'll try it when I have some time.

Thank you for all of your hard work.

**Comment by SteveKunG** [comment]
2.1.0 is out. But you need to backup all your save and config. (More Planets 2.0.14 no longer compatible with 2.1.0)
