### ISSUE TITLE
Dark Asteroids still has loading problems

### ISSUE THREAD

**Issue by bballboy2002** [SteveKunG/MorePlanets#31]
https://pastebin.com/7Hfjfumm
At the end, the error that says dim -41 doesn't exist seems to be related but in the config -41 is Mars Space Station (the one from GalaxySpace). The Dark Asteroids dimension ID is -2554.

**Comment by MJRLegends** [comment]
More planets doesnt use this id

**Comment by bballboy2002** [comment]
Maybe I should have posted my configs:
More Planets: https://pastebin.com/Lth5zgr3
Extra Planets: https://pastebin.com/DD31VLWq
Galaxy Space dimensions: https://pastebin.com/dNsmZVt4

**Comment by MJRLegends** [comment]
All you need to do is change dimension ids as your have over lapping ids

**Comment by MJRLegends** [comment]
Also your log doesnt show anything direct at dark Asteroids...

**Comment by bballboy2002** [comment]
I have looked through other configs too and no mention of dim -41, but what I find especially weird is that it only gives me this error when I try to load dark asteroids

**Comment by bballboy2002** [comment]
line 2796: `[13:38:52] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.IllegalArgumentException: Could not get provider type for dimension -2554, does not exist`

**Comment by bballboy2002** [comment]
Changed the config for what was using -41 because I apparently couldnt load any dimension except Overworld and it work now
Closing issue
