### ISSUE TITLE
[1.12] Crash with new Galacticraft Version

### ISSUE THREAD

**Issue by MasterEnderman** [SteveKunG/MorePlanets#33]
The Game crashes if you try to leave the earth in a rocket.
Forge: 14.23.4.2713
Galacticraft: 4.0.1.181
More Planets: 2.1.2-GC177
Crash Report: https://paste.dimdev.org/yoqewupeje.mccrash

**Comment by SteveKunG** [comment]
I've already fix in dev, I probably release new version at today evening in Thai.
