### ISSUE TITLE
Crash on SiriusB

### ISSUE THREAD

**Issue by Cronosus** [SteveKunG/MorePlanets#4]
http://pastebin.com/HvMDz8we

**Comment by MJRLegends** [comment]
See #2 for the solution for this

**Comment by Cronosus** [comment]
i already found it, thanks
but now are chunk generated very slowly.... but still better than crash.

**Comment by MJRLegends** [comment]
Yeah well blame kcauldron for the crash as it doesnt happen with forge

**Comment by Cronosus** [comment]
yeah, i can't use forgeserver, because needed plugins.. :/

**Comment by MJRLegends** [comment]
Yeah, also try out thermos its better and less buggy as kcauldron

**Comment by Cronosus** [comment]
ok, ill try, thanks
