### ISSUE TITLE
[1.7.10] Diamond Pieces Crafting Bugs

### ISSUE THREAD

**Issue by CyanideCarrot** [SteveKunG/MorePlanets#4]
Two bugs with diamond pieces
1. Small diamond pieces are oredicted as ingotSulfur and large diamond pieces are oredicted as compressedSulfur.
2. A normal compressor turns 9 Sirius B carbon cobblestone into 1 small diamond piece, an electric compressor turns 2 Sirius B carbon cobblestone into 2 small diamond pieces.

**Comment by SteveKunG** [comment]
2. It is intended recipe.
