### ISSUE TITLE
Worlds leaking memory

### ISSUE THREAD

**Issue by Straitlaced2** [SteveKunG/MorePlanets#42]
Hi,
I am running More-Planets-1.12.2-2.0.15-GC181.jar on my server. Besides the minecraft worlds, forge tps reports that 2 worlds have been visited: diona and nibiru. The server produced a debug printout with the text:

[06:10:31] [Server thread/DEBUG] [FML]: The world 20b34212 (world) may have leaked: seen 1750 times.

Apparently this is due to your mod not unloading all chunks when it should.

**Comment by SteveKunG** [comment]
I've already fix this issue in 1.13 branch. I'll push the fix into 2.0.16.
