### ISSUE TITLE
crash on beta with the lib

### ISSUE THREAD

**Issue by KenyMylankca** [SteveKunG/MorePlanets#45]
[crash-2018-07-31_14.29.09-client.txt](https://github.com/SteveKunG/MorePlanets/files/2245109/crash-2018-07-31_14.29.09-client.txt)

**Comment by deltanedas** [comment]
Using these:
Galacticraft 181
Galacticraft Planets 181
MicdoodleCore 181
More-Planets 2.0.16
SteveKunG's Lib 1.0.2
Forge 14.23.4.2758 (Out of date, but yours is 14.23.4.2745)
MultiMC 5
I could not replicate the issue.

**Comment by SteveKunG** [comment]
More Planets 2.1.3 required SteveKunG's Lib 1.0.0 so you don't need to update library. Downgrade will fix it.
