### ISSUE TITLE
An event may down tps

### ISSUE THREAD

**Issue by Mugiwaxar** [SteveKunG/MorePlanets#47]
Hello,
Like usualy, I use to inspect how fine work my server with LagGoggles, and this is what happen since I added the mod More-Planet:
![screenshot](https://user-images.githubusercontent.com/4124999/45158408-35519900-b1e4-11e8-9983-45ba1541b011.png)

An unknow event subscriber seems to use an abnormal amount of time and may result to a loss of tps

Mod version: More-Planets-1.12.2-2.0.16-GC181
ModPack: FTP Revalation + Galacticraft 4.0.1.181

**Comment by Mugiwaxar** [comment]
Here a more detailed screenshot with the complete name of the event:
![sc](https://user-images.githubusercontent.com/4124999/45254760-9eb8df80-b37d-11e8-929c-7ec6ce8758c3.png)

**Comment by SteveKunG** [comment]
Please try this experimental build, Also backup your world!
https://drive.google.com/file/d/129UO5qCCNfLazXN0DL3qwQjIx4DpviF8/view?usp=sharing

**Comment by Mugiwaxar** [comment]
Same problem with this one

**Comment by SteveKunG** [comment]
OK, This should work I think.
https://drive.google.com/file/d/1V8F3KSv6j9Cr6fdH14w5T6t3Ugqg16U8/view?usp=sharing

![2018-09-18_02 02 50](https://user-images.githubusercontent.com/6128413/45644376-d1827680-bae7-11e8-9e25-ab51c7455669.png)
