### ISSUE TITLE
[1.12.2] Forge Crashes While Post-Intitializing Mods (Possible Mod Conflict)

### ISSUE THREAD

**Issue by PulseBeat02** [SteveKunG/MorePlanets#49]
I was loading my big modpack, but it crashed while post - initializing (phase 5/7 I believe). Minecraft and the crash report gave off an error that said "Extra Planets" and "Primalcore". I believe the two mods are conflicting, causing Minecraft Forge to Crash.

Minecraft Version: 1.12.2
Extra Planets Version: 1.12.2-0.4.3
PrimalCore Version: 1.12.2-0.6.92
Forge Version: 14.23.4.2765 

Here is the crash report: https://paste.dimdev.org/rawepedoha.mccrash

Can someone tell me what is going on?

**Comment by An-Sar** [comment]
try adding **_moreplanets:cheese_food_** to the config Machines.HIBACHI_FURNACE_BLACKLIST
