### ISSUE TITLE
[1.11.2 Maybe others] Crash when looking in JEI

### ISSUE THREAD

**Issue by MJRLegends** [SteveKunG/MorePlanets#5]
When trying to look in JEI in my dev workspace as im working on the Compatibility, i got this crash https://pastebin.com/4ZQmVBpF

**Comment by SteveKunG** [comment]
Is this happened only in development?

**Comment by MJRLegends** [comment]
Think so yeah

**Comment by SteveKunG** [comment]
Some other mod has changed `GlStateManager.cullFace` modifier? e.g. public to protected/private

**Comment by MJRLegends** [comment]
Im using jei and Galacticraft and my addon nothing else

**Comment by MJRLegends** [comment]
ping @SteveKunG Sorry to bother you but Any news of this issue :D

**Comment by SteveKunG** [comment]
Is this was solved for you?

**Comment by MJRLegends** [comment]
Not sure i hardly ever test our addon together in MC 1.11.2 as i use MC 1.10.2 mostly for adding new features and bug fixing

**Comment by SteveKunG** [comment]
@MJRLegends This should solved by this https://github.com/SteveKunG/MorePlanets/commit/f0057099fe4a4b01ba8f39ff2d82eb4cb4aa9371

GitHub doesn't include my access transformer.
