### ISSUE TITLE
Koentos and Fronos not showing up in planet selection.

### ISSUE THREAD

**Issue by A-T-L-A-S** [SteveKunG/MorePlanets#50]
Description: =see title=
Minecraft version: 1.12
forge: forge 14.23.4.2759
MicdoodleCore: 4.0.1.181
GC Core/Planets: 4.0.1.181
More Planets: 2.0.17-GC181

Fronos can only be found in the config but not on the curseforge while Koentos is shown on curseforge but can't be found in the config.
Both are not showing up anywhere on the planet map screen.

I hope this is a bug and not planets being removed because I'd really like to explore these two planets (Koentos is a moon I know). :)

**Comment by A-T-L-A-S** [comment]
Also tested in beta version of more Planets.

**Comment by SteveKunG** [comment]
Sorry, I'm not implemented yet (Only blocks/items and some stuff.), due my personal work and time. :(
