### ISSUE TITLE
Venus Dungeon Generation

### ISSUE THREAD

**Issue by barker0522** [SteveKunG/MorePlanets#53]
I'm playing Space Astronomy from the Twitch client, which has moreplanets 1.4.0 and more planets extra 4.0 included.

I'm not sure if this is a bug, or it's just the way it's designed, but after finding 7 dungeons on Venus and getting 5 tier 4 keys from the boss, I have yet to find a single dungeon chest.  I walk down the hallway near the boss room and it always just ends with a wall.  I dig through the wall and don't find anything.

Is it just a low chance that you find the treasure room that you use the key in?

In previous planets I didn't have this issue.

**Comment by MJRLegends** [comment]
Just find another dungeon, sometimes galacticraft bugs out with the spawning in them

**Comment by barker0522** [comment]
So more than 7 dungeons are sometimes necessary?  The map is already expanded pretty big.

Is there a way I can delete that dimension and let it regenerate?

**Comment by barker0522** [comment]
And thank you so much for this mod pack.  I'm loving it.  Great work.

**Comment by barker0522** [comment]
Meh, I just rushed 3 more with the same results, dungeons are generating fully with the exception of the treasure room.

I felt like I was playing diablo again, rushing the same dungeons over and over again haha.

I gave up and cheated in the schematic.  I have really bad luck, this just wasn't going to happening and it was getting boring.

Hopefully the rest of the planets aren't like this.

**Comment by SteveKunG** [comment]
This is intended feature, No treasure chest room generated.
Including Venus, Mercury and Koentus Moon.

**Comment by barker0522** [comment]
Are the higher level rocket schematics still available then?  Previously I only found them in those treasure chests.
