### ISSUE TITLE
Server crash when in traveling to dimension in Spaceship. "Ticking Entity" Crashlog enclosed

### ISSUE THREAD

**Issue by Gamerbolts** [SteveKunG/MorePlanets#54]
Hi there I am working on a modpack with quite a few mods. Included it More Planets. I recently had testers on the server and they were trying to fly to Pluto and other planets. They crashed, I looked it up and saw where you said to do the forge chunk load thing to false. So I did that. They were able to get to Pluto but upon flying back they received a crash to desktop as well as the server crashing. Here is the error log I got server side. https://pastebin.com/EU3H0txg. Is there anything that can be done? I know I have a lot of mods and there may be conflicts but I don't really wanna lose a good exploration mod like More Planets in my modpack. Please let me know. Thanks alot.

**Comment by SteveKunG** [comment]
Please update Galacticraft to this : https://ci.micdoodle8.com/job/Galacticraft-1.7/499/

**Comment by Gamerbolts** [comment]
Apologies I had no idea I had an outdated GC. Thank you for letting me know.
