### ISSUE TITLE
[minor niggle] chat

### ISSUE THREAD

**Issue by ghost** [SteveKunG/MorePlanets#54]
Would it be possible to get a configuration to disable the stuff that shows up in chat when you first load into a world? I'm trying to keep login chat spam at or near zero in my pack.

**Comment by SteveKunG** [comment]
You can, Just disable 'Enable Version Checker' and 'Enable Change Log in Game' in the config.

**Comment by ghost** [comment]
Don't know how I missed that, thanks :)
