### ISSUE TITLE
[Crash] Conflict with OTG

### ISSUE THREAD

**Issue by ghost** [SteveKunG/MorePlanets#55]
https://paste.dimdev.org/gamugogila.mccrash

I traveled to a world with a space warper core in my inventory with the world data from the overworld (which is otg+biomebundle). Upon opening my inventory I got the above crash. Tossing the item out of my hotbar fixes the issue.

**Comment by SteveKunG** [comment]
Please check in 2.0.18 if it has been fixed. Thanks and sorry for slowly bug fixing :(.

**Comment by ghost** [comment]
That file appears to be for galacticraft x.190, I'm using x.181 as it's the current release version of the mod.

**Comment by SteveKunG** [comment]
I always update my mod to use latest version of Galacticraft to prevent incompatible with it.

**Comment by ghost** [comment]
Noted. I guess I'll test this when a new promoted version of galacticraft comes around.
-makes another note to self to not update this mod until then-

**Comment by ghost** [comment]
Finally updated GC to a compatible version and have confirmed this issue is fixed, closing ticket!
