### ISSUE TITLE
1.7.10 Already Decorating Crash (newest version MP & GC) Crash logs enclosed.

### ISSUE THREAD

**Issue by Gamerbolts** [SteveKunG/MorePlanets#55]
Hi again, sorry for bothering you. I updated to GC 499 like you said and when a tester tried going to space (they didn't say which planet according to the log looks like SiriusB) it crashed the server. then crashed it 3 more times each time they tried to log back in while in the dimension. 

Here is the first log: https://pastebin.com/CNWDUFYU
And the 2nd one: https://pastebin.com/rmzJW8GR

I also went into the log to see if I could find anything and saw this:

[23:46:24] [Server thread/INFO]: Unknown net.minecraftforge.common.chunkio.QueuedChunk {
 x: 23
 z: -8
 loader: null
 world: DIM-2548
 dimension: -2548
 provider: stevekung.mods.moreplanets.planets.siriusb.dimension.WorldProviderSiriusB
}
[23:46:24] [Server thread/INFO]: This should not happen. Please report this error to Forge.
[23:46:24] [Server thread/INFO]: Unknown net.minecraftforge.common.chunkio.QueuedChunk {
 x: 23
 z: -8
 loader: null
 world: DIM-2548
 dimension: -2548
 provider: stevekung.mods.moreplanets.planets.siriusb.dimension.WorldProviderSiriusB

I did research on previous issues in your github and saw that this error should have been fixed. So just wanted to let you know what is going on. Wondering if its one of my other mods that is spawning something it shouldn't on the planets. But didn't see any other mod in the log besides GC and MP.

Thank you for your help. ( again :) )

**Comment by MJRLegends** [comment]
See issue #2 to fix this

**Comment by Gamerbolts** [comment]
Thought I had already changed that option, guess it didn't save. Thanks for the help!
