### ISSUE TITLE
Thermal Expansion's Redstone Furnace is randomly turning normal Wood into Infected Charcoal

### ISSUE THREAD

**Issue by ErisyaleLancaster** [SteveKunG/MorePlanets#57]
Hello,
I'm playing on a Server that has Thermal Expansion (and all it's required Mods, obviously.) and GalatiCraft and More Planets installed.

I've run into an issue where the Redstone Furnace will randomly start to convert Wood into the 'Infected Charcoal' that More Planets adds instead of regular Charcoal.
This isn't some custom setting by the Server Admin or my Error as the same Wood will be turned into normal Charcoal by any other type of Furnace.

I'm not sure if the issue lies within Thermal Expansion or More Planets so i decided to report this to both sides.

Or could it just be the Server itself screwing up? :/

And while i'm here, what exactly is the use of Infected Charcoal? as i'm not sure if i should onto it or just get rid of it.

**Comment by Chan0n** [comment]
Still happening, playing on Astroblock modpack.
Happens randomly, restart the server to fix it. But still happens randomly. but not that often. 1-2 times per day.
