### ISSUE TITLE
Game crashes when hovering over spacewarper core with planet id.

### ISSUE THREAD

**Issue by BobRossss** [SteveKunG/MorePlanets#58]
Game crashes when hovering over spacewarper core with planet id on a multiplayer server only.
![Capture](https://user-images.githubusercontent.com/37054224/56084311-288ac880-5df7-11e9-9c04-fe3f875f7a0b.PNG)
[crash-2019-04-13_14.18.23-client.txt](https://github.com/SteveKunG/MorePlanets/files/3076646/crash-2019-04-13_14.18.23-client.txt)

**Comment by SteveKunG** [comment]
Fixed in 2.0.19 and 2.1.6.
