### ISSUE TITLE
? Issue with minecolonies

### ISSUE THREAD

**Issue by ghost** [SteveKunG/MorePlanets#59]
Ok I'm not sure what spawned this, but I'll lay out the scenario:

-Placed builders hut from minecolonies mod
-Started digging out blocks in the way following the construction tape outline
-vanillafix spat this out a bunch of times: https://paste.dimdev.org/bujanoduve.mccrash

No actual crash occurred. If this is the fault of the other mod, let me know and I'll go shove it there.

**Comment by ghost** [comment]
Some further information: the construction tape appears to turn into a sand block from this mod while it's falling, then changes back.

Edit: this appears to change depending on what gets what ID: In a test world looking for an unrelated issue it was nuclear waste with an ID# of 5701

**Comment by SteveKunG** [comment]
Fixed in 2.0.19.

**Comment by ghost** [comment]
https://paste.dimdev.org/gifuxebaje.mccrash

I thought it was fixed too, but this just happened.

**Comment by SteveKunG** [comment]
Fixed in https://github.com/SteveKunG/MorePlanets/commit/510e9417a6a52155248c793de7c2b2ccaa49c3d7
