### ISSUE TITLE
polongnius (maybe other planets too) - chest-room (with spawner)

### ISSUE THREAD

**Issue by Cronosus** [SteveKunG/MorePlanets#6]
hello
Player on my server found little bug on planet polongnius (and maybe others too), he sometimes found room created just from chests (polongnius ancient chest), all bugged and some invisible.
i found one too
![2016-07-06_16 24 31](https://cloud.githubusercontent.com/assets/5349950/16621371/4cbd2cbc-4396-11e6-8b3b-aa7ba0b6599e.png)

**Comment by SteveKunG** [comment]
OK. Can you provide your world seed and coordinate?

**Comment by Cronosus** [comment]
seed: 7029976515901086954
one of coordinates is on screen

**Comment by SteveKunG** [comment]
OK. Please try this version.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2358057-more-planets-mod-v-1-3-1-galacticraft-add-on?page=48#c972

**Comment by Cronosus** [comment]
Nice, fixed.
Thanks :)
