### ISSUE TITLE
Strange bug - crush 1.7.10

### ISSUE THREAD

**Issue by SkySem** [SteveKunG/MorePlanets#60]
Prior to this, Sirius B was a working planet. Alone, too, works.
But now, it is enough to teleport to this planet - and you will get the crash of the server.
Log is attached:  https://pastebin.com/WkqA3Z1d
version game [1.7.10]
server [KCauldron]

**Comment by MJRLegends** [comment]
Change the option "load chunk on request" to false in cauldron.yml

**Comment by SkySem** [comment]
IT WORKS!
This is true happiness.
Thaaaaank!
