### ISSUE TITLE
More Planets Error

### ISSUE THREAD

**Issue by FrostCreeper07** [SteveKunG/MorePlanets#61]
After figuring out one issue now i'm having an issue with this mod [here](https://pastebin.com/nTUKv7D8) is the crash log i have the latest versions of Galacticraft so please help.

**Comment by MokahTGS** [comment]
Is this the same crash?

https://paste.dimdev.org/aqewonaxom.mccrash

If not, I'll open a new issue.

**Comment by BugmanBugman** [comment]
https://paste.dimdev.org/zosiyofasi.mccrash

I got this too!

**Comment by SteveKunG** [comment]
This causes by new GC Inventory system, my tile entities need to be update.

Please use GC build 212 until I update it.

**Comment by SteveKunG** [comment]
2.0.20 and 2.1.7 is out, This should fix the problem.
