### ISSUE TITLE
impossible to lunch the mod

### ISSUE THREAD

**Issue by Zack7292** [SteveKunG/MorePlanets#64]
When i lunch the game with the verison you jsut release (More-Planets-1.12.2-2.0.21-GC224)
it always said "need galcticraftcore / galacticraft planet... 224. but i alreayd isntall this version and i even reinstall it to be sure it wasn't jsut my probleme, but it was still doing this screen to me so its kinda anoying bcs its said i got the 220 instead of the 224 but int he files its clearly said 224 (versions of galacticraft)  so, please can you fix this issue as fast as possible (if you want more information on my downlaods mods in the "mods" folder etc i can simply give u it jsut ask)

**Comment by MrBearLoL** [comment]
I think they uploaded the wrong version. Its the same size as the GC215 version.

**Comment by Zack7292** [comment]
tath could be possible, sinse were human xD

**Comment by olavjens777** [comment]
can confirm

**Comment by SteveKunG** [comment]
This is GC Issue and its happened again. https://github.com/micdoodle8/Galacticraft/issues/3733

**Comment by SteveKunG** [comment]
Fixed for now!
https://ci.micdoodle8.com/job/Galacticraft-1.12/226/
