### ISSUE TITLE
	More-Planets-1.12.2-2.0.21-GC224 Requires GC Core 224

### ISSUE THREAD

**Issue by MokahTGS** [SteveKunG/MorePlanets#66]
Getting an error loading saying that More Planets requires GC Core 224....even though I have 224 installed.  The error message says I have 220.  I do not.

Full mod list: https://pastebin.com/UV3ehTMN

**Comment by SteveKunG** [comment]
Fixed for now!
https://ci.micdoodle8.com/job/Galacticraft-1.12/226/
