### ISSUE TITLE
Release version works, Beta crashes with bad ID error.

### ISSUE THREAD

**Issue by Silvernova115** [SteveKunG/MorePlanets#67]
[crash-2019-08-22_20.58.19-client.txt](https://github.com/SteveKunG/MorePlanets/files/3532776/crash-2019-08-22_20.58.19-client.txt)

**Comment by SteveKunG** [comment]
Install JustEnoughIDs mod.

**Comment by Silvernova115** [comment]
It already is installed

**Comment by Silvernova115** [comment]
Why was this closed this doesnt resolve my issue!?

**Comment by SteveKunG** [comment]
I don't see any issue related to my mod. Just install JustEnoughIDs mod to fix limited IDs issue. (Also I'm not fan of NotEnoughIDs mod by the way.)

**Comment by Silvernova115** [comment]
Well strange. It is already installed and still throwing the error
