### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by bobosGS** [SteveKunG/MorePlanets#69]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  RandomPatches (randompatches-1.12.2-1.18.1.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.1.383.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.236.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 9/4/19 2:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from More Planets (moreplanets)
Caused by: java.lang.NoSuchMethodError: micdoodle8.mods.galacticraft.core.tile.TileEntityAdvanced: method <init>()V not found
	at stevekung.mods.moreplanets.util.tileentity.TileEntityTreasureChestMP.<init>(TileEntityTreasureChestMP.java:60)
	at stevekung.mods.moreplanets.module.planets.diona.tileentity.TileEntityDionaTreasureChest.<init>(TileEntityDionaTreasureChest.java:10)
	at stevekung.mods.moreplanets.client.renderer.ItemModelRenderer.registerCCLRenderer(ItemModelRenderer.java:177)
	at stevekung.mods.moreplanets.proxy.ClientProxyMP.registerPreRendering(ClientProxyMP.java:81)
	at stevekung.mods.moreplanets.core.MorePlanetsCore.preInit(MorePlanetsCore.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1868508896 bytes (1781 MB) / 2986344448 bytes (2848 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2846 Optifine OptiFine_1.12.2_HD_U_E3 87 mods loaded, 87 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                           | Signature                                |
	|:----- |:------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft                 | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCH   | mcp                       | 9.42                     | minecraft.jar                                    | None                                     |
	| LCH   | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2846.jar                    | None                                     |
	| LCH   | forge                     | 14.23.5.2846             | forge-1.12.2-14.23.5.2846.jar                    | None                                     |
	| LCH   | micdoodlecore             |                          | minecraft.jar                                    | None                                     |
	| LCH   | openmodscore              | 0.12.2                   | minecraft.jar                                    | None                                     |
	| LCH   | foamfixcore               | 7.7.4                    | minecraft.jar                                    | None                                     |
	| LCH   | randompatches             | 1.12.2-1.18.1.1          | randompatches-1.12.2-1.18.1.1.jar                | None                                     |
	| LCH   | aroma1997core             | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                 | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCH   | aromabackup               | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCH   | aromabackuprecovery       | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                   | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCH   | jei                       | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                        | None                                     |
	| LCH   | quark                     | r1.6-177                 | Quark-r1.6-177.jar                               | None                                     |
	| LCH   | autoreglib                | 1.3-32                   | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCH   | buildcraftlib             | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCH   | buildcraftcore            | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCH   | buildcraftenergy          | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCH   | mantle                    | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LCH   | natura                    | 1.12.2-4.3.2.69          | natura-1.12.2-4.3.2.69.jar                       | None                                     |
	| LCH   | forestry                  | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                    | None                                     |
	| LCH   | binniecore                | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                 | None                                     |
	| LCH   | binniedesign              | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                 | None                                     |
	| LCH   | genetics                  | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                 | None                                     |
	| LCH   | botany                    | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                 | None                                     |
	| LCH   | extrabees                 | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                 | None                                     |
	| LCH   | extratrees                | 2.5.1.188                | binnie-mods-1.12.2-2.5.1.188.jar                 | None                                     |
	| LCH   | biomesoplenty             | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar    | None                                     |
	| LCH   | buildcraftbuilders        | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCH   | buildcrafttransport       | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCH   | buildcraftsilicon         | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCH   | buildcraftcompat          | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCH   | buildcraftfactory         | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCH   | buildcraftrobotics        | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                     | None                                     |
	| LCH   | codechickenlib            | 3.2.3.357                | CodeChickenLib-1.12.2-3.2.3.357-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | chickenchunks             | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux              | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore                  | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar           | None                                     |
	| LCH   | cofhworld                 | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cookiecore                | 2.0.0                    | cookiecore-1.12-2.0.0.jar                        | 4bbb70ebe391f24f7704e343108a9b21b44c1b10 |
	| LCH   | enderstorage              | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | tconstruct                | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                 | None                                     |
	| LCH   | extrautils2               | 1.0                      | extrautils2-1.12-1.9.9.jar                       | None                                     |
	| LCH   | foamfix                   | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                        | None                                     |
	| LCH   | forgelin                  | 1.8.3                    | Forgelin-1.8.3.jar                               | None                                     |
	| LCH   | forgemultipartcbe         | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | microblockcbe             | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar     | None                                     |
	| LCH   | minecraftmultipartcbe     | 2.6.2.83                 | ForgeMultipart-1.12.2-2.6.2.83-universal.jar     | None                                     |
	| LCH   | galacticraftcore          | 4.0.2.236                | GalacticraftCore-1.12.2-4.0.2.236.jar            | None                                     |
	| LCH   | galacticraftplanets       | 4.0.2.236                | Galacticraft-Planets-1.12.2-4.0.2.236.jar        | None                                     |
	| LCH   | waila                     | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCH   | mekanism                  | 1.12.2-9.8.1.383         | Mekanism-1.12.2-9.8.1.383.jar                    | None                                     |
	| LCH   | teslacorelib              | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | industrialforegoing       | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.12-236.jar       | None                                     |
	| LCH   | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | ironchest                 | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LCH   | journeymap                | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar                      | None                                     |
	| LCH   | mekanismgenerators        | 1.12.2-9.8.1.383         | MekanismGenerators-1.12.2-9.8.1.383.jar          | None                                     |
	| LCH   | mekanismtools             | 1.12.2-9.8.1.383         | MekanismTools-1.12.2-9.8.1.383.jar               | None                                     |
	| LCE   | moreplanets               | 2.0.19                   | More-Planets-1.12.2-2.0.19-GC211.jar             | b3468b224a74e296555ad7efeb35f482e6f445de |
	| LC    | mrtjpcore                 | 2.1.4.43                 | MrTJPCore-1.12.2-2.1.4.43-universal.jar          | None                                     |
	| LC    | nonvflash                 | 1.2.0                    | NoNVFlash-1.12.2-1.2.0.3-universal.jar           | None                                     |
	| LC    | nuclearcraft              | 2.18h                    | NuclearCraft-2.18h-1.12.2.jar                    | None                                     |
	| LC    | openmods                  | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                    | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | openblocks                | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | harvestcraft              | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zf.jar                  | None                                     |
	| LC    | projecte                  | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                      | None                                     |
	| LC    | projectred-core           | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-Base.jar             | None                                     |
	| LC    | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.4.120-compat.jar           | None                                     |
	| LC    | projectred-integration    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar      | None                                     |
	| LC    | projectred-transmission   | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar      | None                                     |
	| LC    | projectred-fabrication    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-fabrication.jar      | None                                     |
	| LC    | projectred-illumination   | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-lighting.jar         | None                                     |
	| LC    | projectred-expansion      | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar       | None                                     |
	| LC    | projectred-relocation     | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar       | None                                     |
	| LC    | projectred-transportation | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar       | None                                     |
	| LC    | projectred-exploration    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-world.jar            | None                                     |
	| LC    | randomtweaks              | 1.12.2-2.7.1.0           | randomtweaks-1.12.2-2.7.1.0.jar                  | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
	| LC    | refinedstorage            | 1.6.15                   | refinedstorage-1.6.15.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LC    | thermalfoundation         | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion          | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalcultivation        | 0.3.3                    | ThermalCultivation-1.12.2-0.3.3.12-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaldynamics           | 2.5.5                    | ThermalDynamics-1.12.2-2.5.5.21-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalinnovation         | 0.3.3                    | ThermalInnovation-1.12.2-0.3.3.12-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | tinkertoolleveling        | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar              | None                                     |
	| LC    | zerocore                  | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                      | None                                     |
	| LC    | immersiveengineering      | 0.12-91                  | ImmersiveEngineering-0.12-91.jar                 | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | teslacorelib_registries   | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                 | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
RandomPatches (randompatches-1.12.2-1.18.1.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.1.383.jar)
  mekanism.coremod.KeybindingMigrationHelper
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.236.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 425.31' Renderer: 'GeForce 920M/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 425.31
	OpenGlRenderer: GeForce 920M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by SteveKunG** [comment]
Update More Planets to latest.
https://www.curseforge.com/minecraft/mc-mods/galacticraft-add-on-more-planets/files/2752029
