### ISSUE TITLE
Dark Asteroids generation completely fails

### ISSUE THREAD

**Issue by CandiceJoy** [SteveKunG/MorePlanets#7]
Crash Report: http://goo.gl/Jkv0ZB
Client log: https://www.dropbox.com/s/46asria8e225ffl/more-planets-crash-fml-client-latest.log?dl=0

I even tried NBT editing my playerdata to put myself back in the overworld so I could at least keep playing the rest of the pack, but something forces me to be in dim -2554 and therefore it forces -2554 to either load or generate, and it just goes into the infinite loop and crashes.

**Comment by wizzahd** [comment]
I get the same error, followed by a server crash. playing on MC 1.7.10, Space Astronomy pack v1.5.2 with latest Galacticraft (+ libraries) and More Planets 1.3.3.

I've been able to work around this by moving my player into dimension 0 using NBTExplorer, but entering the dimension -2554 again inevitably causes the same error.

**Comment by MJRLegends** [comment]
@CandiceJoy this crash has no direct link to its source or the addon, also i dont get it and @wizzahd same applies

**Comment by SteveKunG** [comment]
As @MJRLegends said. I can't find the main problem of this issue.
Can you testing without other GC Add-on?

**Comment by SteveKunG** [comment]
OK. Issue was fixed in the next version.
