### ISSUE TITLE
[1.7.10] Config option for disabling oreGen

### ISSUE THREAD

**Issue by DerMilchkarton** [SteveKunG/MorePlanets#76]
Any chance to get an option for disabling the oregen on the other planets?

Would be great for compatibility with other mods.

**Comment by SteveKunG** [comment]
You want to disable ores on all planets? or just disable each planet?

**Comment by DerMilchkarton** [comment]
Disabling all oregen via the configs would be enough i guess, but if you're able to give config options to disable the ore generation on the planets individually that would be even better :) thanks in advance!

**Comment by SteveKunG** [comment]
OK, I added the config on 1.12.2. Also 1.7.10 has been discontinued for a while.

**Comment by DerMilchkarton** [comment]
Any chance you can backport this to 1.7.10? I'm using GregTech 5u and it's only available for the 1.7.10 version :(

**Comment by SteveKunG** [comment]
Sorry, 1.7.10 is 5 years old.
