### ISSUE TITLE
Unable to use mod

### ISSUE THREAD

**Issue by PlatinumFox** [SteveKunG/MorePlanets#79]
When adding more planets to my mod list the game doesnt even load. it crashes at the launcher and does not leave a crash log. i will post the latest log info when it does crash . not sure what is happening here.
[latest log.log](https://github.com/SteveKunG/MorePlanets/files/4223027/latest.log.log)

**Comment by SteveKunG** [comment]
Some of mod using mixin 0.7.5

**Comment by PlatinumFox** [comment]
I’m sorry I don’t know what you’re asking or what info is needed. A crash log is not created. The launcher just crashes. If you need a mod list I could provide images if that would help. The only file created is the log file.

**Comment by ROMVoid95** [comment]
can you use hastebin or alternative site and post a list of your installed mods (and the mod loader your using) since i see spongeforge and liteloader.

**Comment by PlatinumFox** [comment]
here is an image with all the mods I use
![image](https://user-images.githubusercontent.com/23727270/77384283-63adaf80-6d5b-11ea-8940-d230a53e7211.png)

I am using LiteLoader. i doubt im using spongeforge since i dont know anything about it.
forge version: 1.12.2-14.23.5.2836

**Comment by LemADEC** [comment]
Logs say Mixin was provided by LiteLoader and MorePlanets requires a more recent version.
Try updating LiteLoader or rename it so it comes after MorePlanets.

**Comment by SteveKunG** [comment]
Thank you @LemADEC, as he said you could try update LiteLoader or Voxel Map which it use mixin 0.7.5. I never tested my mod with LiteLoader to be honest.

**Comment by PlatinumFox** [comment]
I never got it to work with LiteLoader unfortunately. luckily voxel map is offered as a forge mod and not a liteloader one (was unaware of this until recently). not using liteloader seems to have fixed the issue.
