### ISSUE TITLE
Unable to edit furnace recipes

### ISSUE THREAD

**Issue by AechtRob** [SteveKunG/MorePlanets#85]
For some reason, using CraftTweaker/ModTweaker/etc/etc I am unable to remove furnace recipes from MorePlanets, eg. this does nothing:

furnace.remove(<moreplanets:nibiru_item:2>);

Nor does this:

val oreCoal = <ore:oreCoal>;
oreCoal.remove(<moreplanets:fronos_ore:6>);

Any reason why the moreplanets recipes seem to override CraftTweaker? I can ADD recipes no problems, just not remove ones the mod introduces. They are stored in vanilla-style registries afaik, so shouldn't need specific support.

**Comment by SteveKunG** [comment]
Legacy version of More Planets 1.12.2 (Below 2.0.x) is no longer supported due to bad codebase and maintenance cost. So it's not worth it to support anymore.
I'd suggest to use newer version (2.1.x+) instead. Thank you.
