### ISSUE TITLE
Ores spawn where they shouldn't

### ISSUE THREAD

**Issue by melody-rs** [SteveKunG/MorePlanets#86]
Fronos and koetonus ores can spawn where they shouldn't be able to.
![2020-05-25_18 10 42](https://user-images.githubusercontent.com/54482069/82858492-e3293d80-9ec8-11ea-8751-1d1950b25e6f.png)

**Comment by SteveKunG** [comment]
How is it spawned? It looks like generated from other mods that using ore dictionary.

**Comment by melody-rs** [comment]
I’m trying to figure out why? None of the other mp ores spawn besides those two
I notice they are from planets that don’t exist yet so I don’t think you put in the spawning requirements yet

**Comment by melody-rs** [comment]
Do Fronos and Koetounus actually exist?  I see pictures of them and even config options for their dim ID's so they seem like they should exist, yet I don't see them in the star map

**Comment by SteveKunG** [comment]
Only Koentus currently available, Also this might be a minor issue and it shouldn't break the game.

**Comment by melody-rs** [comment]
This is still a bug in the latest version. It's a very annoying bug and can absolutely destroy the landscape. Those ores don't actually have predict, from what I can tell, and without any of the worldgen mods in the pack, those ores still spawn.
It's not a minor bug. Or a legacy bug. A minor bug is something that just doesn't really matter, like a button being a pixel off centre or something. This is a bug that ruins the look and feel of the world and destroys caves and early game progression as these ores have higher mining level than normal.
You should fix this, and not dismiss it. That's malpractice. Koetonus and fronos ores still spawn like this regardless of what recent version of more planets is installed.
Yes, the image I provided is a bit exaggerated as I had minerals running, however, these ores still spawn elsewhere throughout the world in large clusters. I'll just be flying past a mountain and just see a blue patch of iron on the side, and it's ugly as hell.

**Comment by SteveKunG** [comment]
Legacy version of More Planets 1.12.2 (Below 2.0.x) is no longer supported due to bad codebase and maintenance cost. So it's not worth it to support anymore.
I'd suggest to use newer version (2.1.x+) instead. Thank you.
