### ISSUE TITLE
Missing entities, biomes, items, blocks,.etc on 1.12.2-2.1.12-GC251

### ISSUE THREAD

**Issue by TopCraft** [SteveKunG/MorePlanets#88]
So I updated the mod to the latest version and it says missing a lot of things when I'm loading into my save. I'm just asking that is it save to play this beta or should I just use the release one. Because it says new look for planets and stuff. I already made a backup of my save so I don't have to worry...
[waim.txt](https://github.com/SteveKunG/MorePlanets/files/4739285/waim.txt)

**Comment by SteveKunG** [comment]
I recommended to use Beta version with JustEnoughIDs (In case of large modpack). A lot of things has been rewrite.

**Comment by beetweenlands** [comment]
i believe I'm getting the same thing, the rockets along with plenty of other stuff do not show up

**Comment by SteveKunG** [comment]
Legacy version of More Planets 1.12.2 (Below 2.0.x) is no longer supported due to bad codebase and maintenance cost. So it's not worth it to support anymore.
I'd suggest to use newer version (2.1.x+) instead. Thank you.
