### ISSUE TITLE
There is no GC118.

### ISSUE THREAD

**Issue by BrotalityG** [SteveKunG/MorePlanets#9]
Ok. So I recently restarted my game, ad reinstalled galacticraft. No other download versio is availible except GC118. This mod needs a GC118. Every other mod I have is set, except this one. Please fix soon!

**Comment by SteveKunG** [comment]
??? https://ci.micdoodle8.com/job/Galacticraft-1.10/118/

**Comment by BrotalityG** [comment]
Thank you

**Comment by BrotalityG** [comment]
Wait no. I'm talking about MorePlanets mod version GC118

**Comment by SteveKunG** [comment]
GC118 its mean build version number of Galacticraft that recommended to play with More Planets.
