### ISSUE TITLE
Space Warper Core disappears after server restart.

### ISSUE THREAD

**Issue by BenGirone** [SteveKunG/MorePlanets#91]
To reproduce:
-Two Warp Pads. 
-One on Earth and one on Mars.
-Link to each other with Warper Cores
-Warp a few times
-Stop server
-Start server
-Crouch and right click on either warp pad

You will see that the Warper Cores have disappeared from the warp pad inventory

**Comment by BenGirone** [comment]
This also affects the battery slot of the Warp Pad

**Comment by BenGirone** [comment]
This can be reproduced in singleplayer as well.

**Comment by BenGirone** [comment]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/modification-development/2694659-tile-entity-inventory-resets-on-world-reload

Looks like an identical issue

**Comment by SteveKunG** [comment]
Cannot reproduce on Beta version, probably you are using legacy.
