### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by CplHartmann** [SteveKunG/MorePlanets#93]
I have an issue with my game crashing on start up
[crash-2020-07-29_19.13.21-client.txt](https://github.com/SteveKunG/MorePlanets/files/4996723/crash-2020-07-29_19.13.21-client.txt)

**Comment by Arekk122** [comment]
looks like you have reached IDs limit, try adding NotEnoughIDs, that should help

**Comment by CplHartmann** [comment]
thank you that fixed my issue
