### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by Arekk122** [SteveKunG/MorePlanets#94]
I am using the latest Gacacticraft and MicdodleCore with MorePlanets 2.1.12 and when I build tier 4 rocket and tried to travel to Diona game crashed on loading. Since then Crash says its server issue: Exception ticking world
When created new world and traveled to Diona with tier 4 creative rocket I had the same issue
Does anyone know what to do? I dont wanna loose my world and start again
I know, its not wise to dont have a backup

**Comment by SteveKunG** [comment]
Any crash log provide?

**Comment by SteveKunG** [comment]
Closing due to inactive.
