### ISSUE TITLE
LivingEvent$LivingUpdateEvent using an entire tick for processing

### ISSUE THREAD

**Issue by MrKiel** [SteveKunG/MorePlanets#95]
Hi, 

We are currently experiencing a somewhat major issue with More Planets taking a considerable amount of time to tick LivingEvent$LivingUpdateEvent (see attached output from laggoggles profiling). 

This server has been running a world for ~2 months since the last reset using More-Planets-1.12.2-2.1.12-GC251. As you can see More Planets is now using >50,000 microseconds (more than a standard tick) to process these events, which is causing substantial problems.

Do you have any advice to rectify or work around this issue please?

![More_Planets_High_Ticks](https://user-images.githubusercontent.com/10761194/89874930-77479e80-dbb4-11ea-9271-f73b77fdb58d.png)

**Comment by Fuzzock** [comment]
Hi,

We are seeing a very similar thing on our server as well which is using More-Planets-1.12.2-2.1.12-GC251:

![image](https://user-images.githubusercontent.com/69691591/90278287-198aaf00-de5f-11ea-85e3-3a203eabccab.png)

It has been about 5 weeks since our last server restart, and are now starting to see server performance issues.

Any advice would be appreciated.

**Comment by SteveKunG** [comment]
Join my discord to get the experimental build for testing : https://discord.gg/6JhEjeY
and go to #more-planets channel.

**Comment by MrKiel** [comment]
Thanks. Testing now.

**Comment by MrKiel** [comment]
![image](https://user-images.githubusercontent.com/10761194/90979384-a4993280-e54c-11ea-8eb6-ed48734caaad.png)
Initial results in test environment look good. 

No major issues found. Tick times appear to be vastly reduced, Shield Generator working correctly. 

We're going to back up our main server and give it a whirl there.

**Comment by Fuzzock** [comment]
![image](https://user-images.githubusercontent.com/69691591/90982932-7888ac00-e562-11ea-8264-c4e84f819916.png)

We are seeing a big improvement here with no issues found so far.

I will keep you updated as the server gets busier today.
