### ISSUE TITLE
Comprehension of  a method in MorePlanets/src/main/java/stevekung/mods/moreplanets/planets/diona/world/gen/structure/StructureDionaMineshaftPieces.java

### ISSUE THREAD

**Issue by 129124** [SteveKunG/MorePlanets#96]
Hi there, when I was reading the code of the function "public void offset(int x, int y, int z)" in MorePlanets/src/main/java/stevekung/mods/moreplanets/planets/diona/world/gen/structure/StructureDionaMineshaftPieces.java, I found it has no Javadoc. My understanding is “returns   the offset of the  filled. @param x the x-coordinate   @param y the y value of the   quaternion.   @param z the z component". Can you please check if this is correct? Thanks.

**Comment by SteveKunG** [comment]
Not really sure, In the original class `StructureMineshaftPieces` doesn't have javadoc for `offset` method as well. So to be honest I don't really know how it work.
