### ISSUE TITLE
Post-Rendering Entity in world

### ISSUE THREAD

**Issue by GoldenDecoder** [SteveKunG/MorePlanets#99]
Issue:
I first went Advent of Ascension (AoA) about this issue first thinking that it had something to do on their end with entity rendering with JEI. They came back to me and said that there may be an issue with MorePlanets and after looking at the log it may be an issue with SteveKungLib over the team here with MorePlanets. However, I figure I would start here since both entities are tied together. Anyhow, when clicking on certain entities (tested w/ Silver Coin, Crystocore,  and in this case Raxxan) an exception is caught: stevekung.mods.stevekunglib.utils.client.event.RenderEntityOverlayEvent@572d1d84: java.lang.NullPointerException: null causing the game to eventually crash. I'll attached both log and crash report below.

Mod Versions:
Steve Version: SteveKunG's-Lib-1.12.2-1.1.9
More Planets Version: More-Planets-1.12.2-2.1.14-GC261

Steps to Reproduce Issue:
1. AoA (3.3.5), ExtraPlanets, JEI, JER, and SteveKungLib installed on client and server
2. Search up one of the entities above in JEI
3. Click on the entity
4. It will begin to open a menu which will then lead to client side crash

Log:
[latest.log](https://github.com/SteveKunG/MorePlanets/files/5192536/latest.log)
Crash Report:
[crash-2020-09-08_21.40.19-client.txt](https://github.com/SteveKunG/MorePlanets/files/5192537/crash-2020-09-08_21.40.19-client.txt)

Crash did happen on server side, but affects were only shown on client-side

**Comment by SteveKunG** [comment]
Please try the experimental build in my discord :
https://discord.gg/6JhEjeY

**Comment by GoldenDecoder** [comment]
Fixed, thank you for fixing this!

**Comment by SteveKunG** [comment]
Fixed in 2.2.0
